### ISSUE TITLE
<PRUEBA> Fecha de termino mayor al año en curso

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#104]
Estimado:

Esta prueba consiste en poder pasar una actividad de un año por ejemplo 2019 al 2020.

**Comment by felipedonoso** [comment]
Al momento de aprobar la solicitud de cambio, entrega un mensaje de error:

Proyecto: 1900042003

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/7386d36a-2db7-4764-89a0-d8018d286465)

Se reviso si es que el proyecto estuviera repetido en la BD de Testing, lo cual fue negativo no estaba repetido

HDA_PROYECTO:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/b946dc7d-0436-472c-bba6-400fa8ff142a)

HDA_MOVIMIENTOS:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/ba706915-e048-400c-ab6b-d3ffd6e4047e)


@pabloespinoza es otro el motivo del error

@danteghirardelli  puedes colocar el detalle de tus pruebas en esta tarea.

Atte, Pillín

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Para el Proyecto N° 1900042003 se buscaba aprobar la Solicitud de Cambio.
El cambio se refería en cambiar las Fechas Fin(pasar al 2019) y Horarios.
Esto para las Competencias, Asignación Beneficiario y Gastos en Bienes y Servicios.
Al presionar "Guardar" en ### Confirmar Envío sistema indica "ERROR:Servicio Converges no disponible (config),vuelva a intentarlo más tarde ."

Llega correo informando "Solicitud de Cambio Alto Rendimiento" . 9:55 hrs 24/01/19

![image](https://user-images.githubusercontent.com/21196249/51680686-359ad700-1fc1-11e9-832a-b1cce24e4f5f.png)

**Comment by pabloespinoza** [comment]
Estimados, el error se produce debido a que en Converges quedó registrado con un rut de federación distinto, por que ese proyecto se cargo cuando cambiaron el rut de ADO.
Saludos.

**Comment by felipedonoso** [comment]
@danteghirardelli favor de continuar las pruebas

**Comment by felipedonoso** [comment]
Se aprueba el proyecto: **1900042006**

[Proyecto - 1900042006.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/2812686/Proyecto.-.1900042006.pdf)

Realizando una ampliación del plazo:

**Comment by danteghirardelli** [comment]
### Modificar Proyecto N° 1900042005
Nombre 	<INFORMÁTICA IND> Art. 1º ley 19135 Fed. Dep. Nacional
### Reporte Antes SC
[1900042005_AntesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/2813260/1900042005_AntesSC.pdf)
![image](https://user-images.githubusercontent.com/21196249/51992774-63ce5a00-248c-11e9-8bc9-9968521ce55b.png)
![image](https://user-images.githubusercontent.com/21196249/51992789-6a5cd180-248c-11e9-969d-6590c58e2369.png)
![image](https://user-images.githubusercontent.com/21196249/51992797-6df05880-248c-11e9-977c-22e3c9aad2b3.png)
![image](https://user-images.githubusercontent.com/21196249/51992814-72b50c80-248c-11e9-915c-67685ef3e88b.png)
![image](https://user-images.githubusercontent.com/21196249/51992863-895b6380-248c-11e9-94d6-1ccd25d70c04.png)
![image](https://user-images.githubusercontent.com/21196249/51992925-a6903200-248c-11e9-9e8d-a71b5afd7caf.png)
![image](https://user-images.githubusercontent.com/21196249/51992935-ab54e600-248c-11e9-98c1-5005201d3320.png)
![image](https://user-images.githubusercontent.com/21196249/51992947-b0199a00-248c-11e9-9a31-1d193b3e4352.png)
![image](https://user-images.githubusercontent.com/21196249/51992951-b4de4e00-248c-11e9-8f24-b7964333cb25.png)
![image](https://user-images.githubusercontent.com/21196249/51992972-ba3b9880-248c-11e9-8091-930924f493e4.png)
![image](https://user-images.githubusercontent.com/21196249/51992982-bf98e300-248c-11e9-92c5-15926e28323d.png)
![image](https://user-images.githubusercontent.com/21196249/51993056-e22afc00-248c-11e9-922d-e3bfca6bfce5.png)
![image](https://user-images.githubusercontent.com/21196249/51993065-e6571980-248c-11e9-80b5-d7fcfb554c82.png)
![image](https://user-images.githubusercontent.com/21196249/51993075-ebb46400-248c-11e9-914c-daf7bc133884.png)
![image](https://user-images.githubusercontent.com/21196249/51993083-f1aa4500-248c-11e9-9d43-c1872c770069.png)
![image](https://user-images.githubusercontent.com/21196249/51993097-f66ef900-248c-11e9-9c42-a2329421460f.png)
![image](https://user-images.githubusercontent.com/21196249/51993108-fa9b1680-248c-11e9-956d-5e1ddec668ea.png)
![image](https://user-images.githubusercontent.com/21196249/51993119-ff5fca80-248c-11e9-8be3-5f61cf9805b4.png)
![image](https://user-images.githubusercontent.com/21196249/51993142-05ee4200-248d-11e9-9bca-7b0c17f7dc69.png)
![image](https://user-images.githubusercontent.com/21196249/51993163-0c7cb980-248d-11e9-9c7f-ec884bd715b7.png)
![image](https://user-images.githubusercontent.com/21196249/51993174-10a8d700-248d-11e9-97c8-564328174587.png)
![image](https://user-images.githubusercontent.com/21196249/51993187-16062180-248d-11e9-934a-d7d703a6b00b.png)
### Después de SC
[1900042005_DespuesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/2813290/1900042005_DespuesSC.pdf)

@felipedonoso @pabloespinoza 
Se realizó la prueba que me solicitaron.
### Conclusión
Los cambios se ven reflejados.
Se adjunta Reporte antes y después de la SC.

**Comment by felipedonoso** [comment]
### Creación de 02 productos:

1. Crear gastos nuevos.
2. Crear excepción  para un producto.
3. Crear excepción para un segundo producto con mes mayor que el anterior.
4. Validación fechas topes en los formularios que dispongan del campo fecha y no por mes.
5. Crear excepción antes de la SC y luego eliminarla.

**Comment by felipedonoso** [comment]
**Pruebas a realizar:**

1. Se creará una excepción.
2. Se creará una SC.
3. Se rechazará las SC.

Creando la excepción: En la parte de mes fin no se despliega nada.

![image](https://user-images.githubusercontent.com/5757157/52053321-d0526300-2537-11e9-9ad2-649c5deba2ca.png)

**NOTA**: Lo que quiere decir es que solamente se podrá realizar una excepción para un producto.

Se creará un nuevo proyecto.

![image](https://user-images.githubusercontent.com/5757157/52053951-9da96a00-2539-11e9-864f-9b423aa5c427.png)

El producto es de nivel Internacional y no debería pedir la competencia:

![image](https://user-images.githubusercontent.com/5757157/52053987-c16cb000-2539-11e9-960f-1f2f36022047.png)

Se agregará la competencia para poder avanzar.

**No pude crear una excepción de tiempos de ejecución.**

**Cuando hay una SC:**

![image](https://user-images.githubusercontent.com/5757157/52075138-3fe14600-256a-11e9-8737-1f5d352d8f4e.png)

**Se eliminará la SC, con el fin de poder crear una excepción de Sc:**

No fue posible crear una excepción.

![image](https://user-images.githubusercontent.com/5757157/52075498-33112200-256b-11e9-90c3-f7e30e20aedc.png)

**Comment by danteghirardelli** [comment]
Se crea nuevo Proyecto ### Todo Cambio QA N° 1900042014
![image](https://user-images.githubusercontent.com/21196249/52067108-a78e9580-2558-11e9-86be-a96b385d8907.png)
### Productos
![image](https://user-images.githubusercontent.com/21196249/52068952-829c2180-255c-11e9-8176-dbde2c5ea470.png)
![image](https://user-images.githubusercontent.com/21196249/52067034-7c0bab00-2558-11e9-84a5-db39f129384e.png)
Reporte Antes SC
[Proyecto - 1900042014_AntesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/2818052/Proyecto.-.1900042014_AntesSC.pdf)
### Crear SC Entrenamiento y Concentraciones
![image](https://user-images.githubusercontent.com/21196249/52069503-9ac07080-255d-11e9-9936-40eca5750fd5.png)
![image](https://user-images.githubusercontent.com/21196249/52069574-ba579900-255d-11e9-847a-0670a1347a56.png)
![image](https://user-images.githubusercontent.com/21196249/52069642-e6731a00-255d-11e9-9780-7ec1617f7d5e.png)
![image](https://user-images.githubusercontent.com/21196249/52069682-00146180-255e-11e9-9c7c-9679912fc7bd.png)
![image](https://user-images.githubusercontent.com/21196249/52069757-26d29800-255e-11e9-9f5e-80b4977f2981.png)
![image](https://user-images.githubusercontent.com/21196249/52069794-38b43b00-255e-11e9-9f79-1d5854043d1d.png)
![image](https://user-images.githubusercontent.com/21196249/52069861-5c778100-255e-11e9-85a3-dc2d0499b65f.png)
![image](https://user-images.githubusercontent.com/21196249/52069926-803ac700-255e-11e9-8a6f-81e1a79a4d6b.png)
![image](https://user-images.githubusercontent.com/21196249/52070034-c42dcc00-255e-11e9-9731-4b95e3bdc7ca.png)
![image](https://user-images.githubusercontent.com/21196249/52070113-e293c780-255e-11e9-8a57-eefe063011e9.png)
![image](https://user-images.githubusercontent.com/21196249/52070236-225aaf00-255f-11e9-87e3-fd49cc9f10d6.png)
![image](https://user-images.githubusercontent.com/21196249/52070415-8bdabd80-255f-11e9-9e64-7bbf3a93b744.png)
### Enviar SC
![image](https://user-images.githubusercontent.com/21196249/52070658-14f1f480-2560-11e9-8264-a03e520c4792.png)
![image](https://user-images.githubusercontent.com/21196249/52070679-20ddb680-2560-11e9-9114-cae0c31fd0e3.png)
![image](https://user-images.githubusercontent.com/21196249/52070707-3357f000-2560-11e9-85a3-780e19a6c1de.png)
### Administración
![image](https://user-images.githubusercontent.com/21196249/52070874-96e21d80-2560-11e9-84b2-b260ec5095fc.png)
![image](https://user-images.githubusercontent.com/21196249/52070939-b711dc80-2560-11e9-94f9-7f74afc0eeb2.png)
![image](https://user-images.githubusercontent.com/21196249/52071042-ede7f280-2560-11e9-94d3-b978cfd05514.png)
![image](https://user-images.githubusercontent.com/21196249/52071095-0d7f1b00-2561-11e9-831e-78b4cb323ee6.png)
![image](https://user-images.githubusercontent.com/21196249/52071185-3b645f80-2561-11e9-861c-6de498bf67d4.png)
### Reporte Después SC
[Proyecto - 1900042014_DespuesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/2818264/Proyecto.-.1900042014_DespuesSC.pdf)

@felipedonoso @pabloespinoza 

### Conclusión
Se creó nuevo Proyecto y se le realizó la SC al Producto Entrenamiento & Concentraciones.
No se desplegaron errores tanto en Sistema como Reportes.

**Comment by felipedonoso** [comment]
Se revisará el reporte: 

Se pueden visualizar los 02 flujos año 2019 y 2020:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/e449ab3c-98cb-45c0-a330-5e0e3d15f4ab)

Esta rico para ser pasado a producción.
