### ISSUE TITLE
Mejoras a la nueva plataforma Informática - 4.- "Ícono "Historial de Cambios"

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#18]
Esta tarea es la más simple que será cambiar el nombre que despliega el ícono al pasar el cursor:

![image](https://cloud.githubusercontent.com/assets/5757157/19156498/7328f47a-8bb8-11e6-9f88-70ba749cfec9.png)

Dice: Historial de Cambios
### Debe decir: Historial de estados del proyecto

**Comment by felipedonoso** [comment]
@pabloespinoza  esta es la tarea pequeña que te mencionaba para pasar a producción en conjunto con la tarea de Objección #21

**Comment by pabloespinoza** [comment]
@felipedonoso @danteghirardelli  versión con la modificación se encuentra en QA y Producción.

**Comment by felipedonoso** [comment]
Se reviso en producción y el cambio fue satisfactorio se cierra la tarea en producción
