### ISSUE TITLE
Mejoras a la nueva plataforma Informática 5.- "Ícono de "Solicitud de modificación"

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#19]
Revisar el contenido del entregable de la Solicitud de Cambio, y revisar los errores para que puedan utilizarla dentro de la segunda semana de enero 2017.

**Comment by felipedonoso** [comment]
@pabloespinoza favor de revisar esta tarea con lo que tiene entregado los chiquillos de SC

**Comment by felipedonoso** [comment]
@pabloespinoza como lo conversamos favor de dejar en QA para revisar con @danteghirardelli el estado de la SC

**Comment by felipedonoso** [comment]
@danteghirardelli revisemos los proyectos que se encuentren en estado "Aprobado" y realizaremos solicitudes de cambio.

Habría que realizar lo siguiente:

1. Modificar un gasto en personal y llevarlo a bienes y servicios.
2. Realizar la inversa desde bienes y servicios hacia personal.

Lo ideal es que el traspaso del monto de un item a otro corresponda al 5% del costo del producto.

**_@danteghirardelli tú crearas un SC para este proyecto: 1600042187_**

**Comment by danteghirardelli** [comment]
@felipedonoso 

Yo hago Punto 2
#corta

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Proyecto 1600042187
[Proyecto - 1600042187.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/534527/Proyecto.-.1600042187.pdf)

![image](https://cloud.githubusercontent.com/assets/21196249/19452111/2635559c-9486-11e6-98f6-855b40b445ae.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19452164/5fc58264-9486-11e6-8de2-3f085f74af72.png)

## Generar Solicitud de Cambio 

![image](https://cloud.githubusercontent.com/assets/21196249/19452292/ea4813f2-9486-11e6-9306-274eea0a6a25.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19452825/eafc450a-9488-11e6-9611-4705f8cc9308.png)

## Total antes de la SC $8.280.000 Menos 5% $414.000 = $7.866.00 Dividido por 92 días = $85.500.-

![image](https://cloud.githubusercontent.com/assets/21196249/19452837/f8de61da-9488-11e6-8b63-c77c19009c20.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19452847/ff266a74-9488-11e6-8fa1-3ebe0fa02c77.png)


## Crear Nuevo Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/19453149/5d6bba52-948a-11e6-80d3-d0d3cdfad728.png)


![image](https://cloud.githubusercontent.com/assets/21196249/19453200/a04a0aa4-948a-11e6-828c-7b8563162567.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19453245/cec753b4-948a-11e6-9dba-828b54163a52.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19454908/53433080-9491-11e6-88a9-fe6f632400c7.png)



![image](https://cloud.githubusercontent.com/assets/21196249/19453413/88062580-948b-11e6-9b37-825a9f961387.png)


![image](https://cloud.githubusercontent.com/assets/21196249/19453466/c2afeb26-948b-11e6-9e3d-e7a6332a4e3e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19453559/296fafc2-948c-11e6-9ae6-68335cc1cee8.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19453682/a73b0fb4-948c-11e6-8b50-b9d63b577985.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19453760/f4fab2f4-948c-11e6-829a-3058cddb879d.png)


## Ir a Producto

Listado de Gasto de Administración
![image](https://cloud.githubusercontent.com/assets/21196249/19453855/57a1fd18-948d-11e6-8522-57bd5a37e452.png)

## Asignar Beneficiario

![image](https://cloud.githubusercontent.com/assets/21196249/19454214/a659c250-948e-11e6-83db-11dc3df4d972.png)

Se edita Gasto Personal
![image](https://cloud.githubusercontent.com/assets/21196249/19454310/05e072fa-948f-11e6-8710-39c20fda6426.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19454406/6367bc3a-948f-11e6-9607-e71fbdf05826.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19454455/8fcf8ca8-948f-11e6-906d-63b90ddc94a3.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19454502/bc5f92a4-948f-11e6-9044-4379641f60b7.png)


## Enviar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/19454612/3d3f0742-9490-11e6-94f1-5ed195fdaeae.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19454717/9ce747ae-9490-11e6-8b81-1e31e9bc4e1f.png)

Envía mensaje:##  Se ha enviado la solicitud asociada al producto "Prueba de Entrenamiento y Concentraciones".

Se envía la SC de Cambio.

**Comment by felipedonoso** [comment]
@danteghirardelli ahora favor de seguir el flujo hasta la Aprobación de la SC y adjuntar el reporte y comparar

**Comment by felipedonoso** [comment]
# SC Proyecto: 1600042191

Montos del proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/19478829/6e935c3c-951a-11e6-8175-1dae89a8e0f1.png)

### Detalle de los productos:

![image](https://cloud.githubusercontent.com/assets/5757157/19478797/493db8d8-951a-11e6-896d-8372cb62deda.png)

Creando la SC:

![image](https://cloud.githubusercontent.com/assets/5757157/19479132/ccfbdf0a-951b-11e6-8439-eaf43ba9ffd2.png)

**Ortografía:**

![image](https://cloud.githubusercontent.com/assets/5757157/19479187/fb3ce224-951b-11e6-8bdd-280882a15215.png)

### Se envía la SC sin modificar nada:

![image](https://cloud.githubusercontent.com/assets/5757157/19479583/e2818666-951d-11e6-886b-9ece43b6e2a8.png)

### Revisando la SC en Administración:


![image](https://cloud.githubusercontent.com/assets/5757157/19479658/4303f0b4-951e-11e6-9342-6b9ae838288a.png)


## Conclusión:

1. Se pudo enviar una SC sin modificar ningún gasto.
2. Al momento de revisar la SC no aparece el icono de aprobar.

1.-R: Debería indicar una alerta: "¿Esta seguro que desea enviar la SC sin documentos adjuntos y sin modificar los gastos en el producto?


2.-Debería aparecer el botón de aprobar/rechazar la SC.

**Comment by felipedonoso** [comment]
# SC Proyecto: 1600042173:

## Productos:

![image](https://cloud.githubusercontent.com/assets/5757157/19480513/02b55b8a-9521-11e6-8350-4ffc158cadb4.png)

### **Creando _SC:**

![image](https://cloud.githubusercontent.com/assets/5757157/19480552/2869a0a2-9521-11e6-8cc3-7cb5678717cf.png)


### Se envía  SC:

![image](https://cloud.githubusercontent.com/assets/5757157/19480735/e09e63ba-9521-11e6-979f-6341c268512f.png)

## Ahora revisando en la Administración:

![image](https://cloud.githubusercontent.com/assets/5757157/19481772/748b94c8-9525-11e6-9b1f-1dd7c816054c.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Aprobar Solicitud de Cambio ->Proyecto 1600042187 desde Administración.

![image](https://cloud.githubusercontent.com/assets/21196249/19480175/b170a870-951f-11e6-9ebc-fb1e7edfe716.png)

## Resumen Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/19480268/1d12de40-9520-11e6-9566-0115a66c145c.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19480919/9f093640-9522-11e6-8da4-b057d28501f0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19480934/a68ecee8-9522-11e6-81f7-3fef7331d287.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19480939/acb3d20a-9522-11e6-9deb-dd776e2eb2bb.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19480948/b294c1e8-9522-11e6-84e6-fd8c898a614c.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19480952/b8f4d352-9522-11e6-8148-a860bc849599.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19480960/c01a0d32-9522-11e6-8374-eff5d6281866.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19480967/c6a57984-9522-11e6-89a2-2bf32a7bfaa4.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19480976/cedf0836-9522-11e6-87b3-9216424154b4.png)

## Al enviar la aprobación de la Solicitud de Cambio sistema envía:
10.15.1.51 dice:
error
![image](https://cloud.githubusercontent.com/assets/21196249/19481007/e1c23eb4-9522-11e6-85bb-a37f45c1c38b.png)

Continuaré con otro Proyecto para intentar realizar una SC para posteriormente aprobarla.

**Comment by felipedonoso** [comment]
# SC Proyecto: 1600042183:

![image](https://cloud.githubusercontent.com/assets/5757157/19482189/b2468a4c-9526-11e6-825c-575a42525a8e.png)
### 

### En esta revisión solo se modificará los horarios de los Beneficiarios:

### La prueba concluye ya que no se puede modificar los gastos:

![image](https://cloud.githubusercontent.com/assets/5757157/19482282/07c27db4-9527-11e6-83aa-bd0138e24351.png)

En el reporte se observa que hay gastos asociados al producto mencionado:

**Se adjunta reporte:** 
[Proyecto - 1600042183.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/536545/Proyecto.-.1600042183.pdf)

**_Ahí se visualiza los gastos en Personal y Bienes y Servicios:_**
![image](https://cloud.githubusercontent.com/assets/5757157/19482422/7b1aa728-9527-11e6-9611-91e726681a27.png)

**Comment by felipedonoso** [comment]
@pabloespinoza, con la versión que esta disponible en Qa para revisar la SC, en ninguna prueba pudimos un caso de éxito:

1. Por parte de @danteghirardelli  hizo la prueba final hasta la aprobación y ocurrió un error:
2. Por mi parte envié la SC sin hacerlos y se pudo enviar pero no aparece el botón de Aceptar/Rechazar.
3. También al subir un documento ocurre algo similar al punto 2.
4. Por último, un caso más particular es de un proyecto el cuál al momento de modificarlo, no me permitió(No aparecen los iconos) y al revisar el reporte se ve claramente que si tiene gastos.

### Entonces habría que revisar Pablo la versión publicada en los puntos:

**1 y 4.**

**Y mejoras en el: 2 y 3.**

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Proyecto 1600042188
![image](https://cloud.githubusercontent.com/assets/21196249/19491376/17c18256-9549-11e6-91bb-1c1ea55aceac.png)

## Productos disponibles para Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/19491402/30065b02-9549-11e6-9ad3-6efe68a4a1e5.png)

## Generar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/19491421/4a5a65d4-9549-11e6-94ba-af326b7fac1f.png)

## Se ingresa Código HTML
![image](https://cloud.githubusercontent.com/assets/21196249/19491448/614ac0ae-9549-11e6-8a44-c880794b5a02.png)

## Sistema envía mensaje:
Ha ocurrido un problema, asegúrese de ingresar todos los campos que sean requeridos.
![image](https://cloud.githubusercontent.com/assets/21196249/19491486/856a15ac-9549-11e6-9369-2dd0c36f1cd7.png)

## Se modifica el Motivo de la solicitud:
![image](https://cloud.githubusercontent.com/assets/21196249/19491505/994860ec-9549-11e6-990e-64f75eb04a26.png)

## No realiza la acción.
Se presiona “Cancelar”
![image](https://cloud.githubusercontent.com/assets/21196249/19491522/ab27fe80-9549-11e6-8414-a83b131ad230.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19491537/b3a44c4e-9549-11e6-9f75-84c9431de17c.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19491545/ba920ff0-9549-11e6-8e49-beb6f0f6ac44.png)

## Asignación Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/19491566/cd588254-9549-11e6-858c-05b8e80d6b19.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19491582/d5f49c86-9549-11e6-9967-2bb2733324df.png)

## Se elimina SC incompleta
![image](https://cloud.githubusercontent.com/assets/21196249/19491602/ec270b38-9549-11e6-8b63-4ac0bf37dab7.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19491612/f438e800-9549-11e6-9605-13e314487a42.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19491617/fafc74b8-9549-11e6-8ec8-75dada409265.png)

## Se generará Solicitud nueva para el mismo proyecto 1600042188
![image](https://cloud.githubusercontent.com/assets/21196249/19491646/19800e72-954a-11e6-944d-0d7b33171313.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## URLs a utilizar
--------------

INDE 11
http://10.15.1.51/AltoRendimientoQA
RUT:16645373
Clave:federacion2016                          

INDE 12
http://10.15.1.51/AdministracionSC
RUT:153149682
Clave:Nov0915,


INDE 12
http://10.15.1.51/AdministracionQA    -->Versión de Producción con los Cambios
RUT:153149682
Clave:Nov0915,

**Comment by felipedonoso** [comment]
@danteghirardelli favor de realizar la siguiente SC al proyecto: 1600042188

###  Entrenamiento y concentraciones:

1.- Cambiar la fecha del producto. 
2.- Cambiar el horario a un Gasto en personal.
3.- Modificar el sueldo a un gasto en personal ejemplo: de Enero a Marzo sueldo mensual de 1 millón cambiar a Enero a Junio(Fecha tope del producto) entonces sería 3 millones % en 6 meses.
4.- Modificar un gasto en Bienes y servicios que contemple el 5% y ese diferencia crear un gasto en personal. De no existir hacer la inversa de Personal a Bienes y Servicios.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Me envía este mensaje:
Error al procesar la solicitud.

![image](https://cloud.githubusercontent.com/assets/21196249/19525952/17b6254a-95f9-11e6-9e0a-a7625b8cb103.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Pablo problema solucionado.
Muchas gracias.

![image](https://cloud.githubusercontent.com/assets/21196249/19526151/dbacc404-95f9-11e6-826d-2b78a74d63a5.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Reporte antes de los cambios.
[Proyecto - 1600042182.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/539531/Proyecto.-.1600042182.pdf)


## Se realizará SC al proyecto "Suicide Squad" --> 1600042182
![image](https://cloud.githubusercontent.com/assets/21196249/19526716/b23306ea-95fb-11e6-9895-0c9fd2b3a685.png)

## Producto Entrenamiento y Concentraciones
![image](https://cloud.githubusercontent.com/assets/21196249/19526994/bbfbaeba-95fc-11e6-88f0-3ed2c8101fda.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19532890/f71b4a0c-9613-11e6-9d12-c179ddcb1ae1.png)

## Despliega este mensaje:
Ha ocurrido un problema, asegúrese de ingresar todos los campos que sean requeridos.

![image](https://cloud.githubusercontent.com/assets/21196249/19532909/09f963c0-9614-11e6-8625-4c3ef587734c.png)

**Comment by felipedonoso** [comment]
@danteghirardelli como lo conversamos, favor crear una SC y modificar los siguientes datos de un proyecto:

1. Ubicación de un producto.
2. Geolocalización de las actividades realizadas por un gasto en personal.
3. Modificar Horario de un Beneficiario.
4. Geolocalización de un gasto en Bienes y Servicios.

### Yo revisare el proyecto 1600042183, todo esto en el sitio:

**INDE 12(SC)QA Nueva SC**
_http://10.15.1.51/AdministracionSC
RUT:153149682
Clave:Nov0915,_

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Realizar pruebas SC Proyecto 1600042176
![image](https://cloud.githubusercontent.com/assets/21196249/19561582/9feb288c-96af-11e6-81d7-2ec93d883140.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19561592/a9612664-96af-11e6-8c86-b646c6ea4001.png)

Sin el ícono de Solicitud de Cambio no se puede realizar la acción.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza

## Realizar pruebas SC Proyecto 1600042175 -->SC Capacitacion 5%
![image](https://cloud.githubusercontent.com/assets/21196249/19574212/afc60fa8-96df-11e6-8b61-a1d7bbe8373a.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19574220/b8ec9994-96df-11e6-8961-885309bb3e16.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19574239/c86067fc-96df-11e6-95eb-fae67178c46b.png)

Sin el icono de Solicitud de Cambio no se puede realizar la acción.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Se continua con la prueba SC
Proyecto 1600042172
![image](https://cloud.githubusercontent.com/assets/21196249/19600253/9dafc3ae-977a-11e6-8ab2-5c73e60edf0c.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19600265/a46623d2-977a-11e6-9e7f-e3b3278ae17d.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19600269/aa8975e8-977a-11e6-9631-1cedf8553df7.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19600274/b08daf36-977a-11e6-9fd7-debeec28c64c.png)


## Se elimina la Solicitud Incompleta.
![image](https://cloud.githubusercontent.com/assets/21196249/19600296/c576d5bc-977a-11e6-9f32-3a2452785d68.png)

## Cambió sin razón alguna el Monto del Producto de $210.920 a $240.920.-

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Se generará la Nueva SC
![image](https://cloud.githubusercontent.com/assets/21196249/19601944/9fe322b8-9781-11e6-95f8-7da10d3d5661.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19601957/a896f998-9781-11e6-91af-0cac94379043.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19601965/b0a560b6-9781-11e6-92b8-8c26595f806d.png)

Sistema indica:
“Ha ocurrido un problema, asegúrese de ingresar todos los campos que sean requeridos”.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Administración SC QA

![image](https://cloud.githubusercontent.com/assets/21196249/19609213/45f862c4-97ac-11e6-85a1-ff4d8298662a.png)

Mensaje: "Se ha producido un error interno. Si persiste favor comunicarse con el Administrador"

Credencial
RUT:153149682
Clave:Nov0915,

**Comment by felipedonoso** [comment]
@danteghirardelli favor de aprobar las SC de los proyectos que se encuentren en estado SC enviada en la bandeja de administración:

1- Aprobar una Sc.
2- Rechazar una Sc.

### Favor de sacar un reporte antes de aprobar la SC:

**Comment by felipedonoso** [comment]
No aparecen los iconos para crear la SC:

![image](https://cloud.githubusercontent.com/assets/5757157/19647668/a21ba09a-99d5-11e6-9c25-9d4bd474c021.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Se aprobará una Solicitud de Cambio
Proyecto 1600042168
![image](https://cloud.githubusercontent.com/assets/21196249/19649112/ee268e82-99da-11e6-9757-1642fd815b0d.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19649119/f8373c32-99da-11e6-87eb-5a0c9598a003.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19649126/feaa99ce-99da-11e6-898b-518a124d5ef1.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19649130/050709a6-99db-11e6-90c3-0393c8e2df25.png)

## Campos Nombre, Proyecto y Gastos vacíos.

Proyecto – Movimiento
![image](https://cloud.githubusercontent.com/assets/21196249/19649629/e6f16eaa-99dc-11e6-83ed-4a11e909603a.png)
## Campos en Sección Movimiento quedan Sin Datos y mensaje mal escrito.

Reporte antes de la SC
[Proyecto - 1600042168.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/548103/Proyecto.-.1600042168.pdf)

Proyecto – Rendición
![image](https://cloud.githubusercontent.com/assets/21196249/19650227/e03c91be-99de-11e6-80f9-dbd572f3647f.png)
Campos en Sección Rendición quedan sin datos y mensaje mal escrito.

## Producto Original
![image](https://cloud.githubusercontent.com/assets/21196249/19651382/fb4746f8-99e2-11e6-8d89-adf03287cb63.png)

## Beneficiarios
![image](https://cloud.githubusercontent.com/assets/21196249/19651418/200f0fde-99e3-11e6-8a34-97100477fab4.png)

## Producto Solicitud
![image](https://cloud.githubusercontent.com/assets/21196249/19651664/3337feb2-99e4-11e6-8ca4-d2b98730554c.png)

## Beneficiarios
![image](https://cloud.githubusercontent.com/assets/21196249/19651677/472effa6-99e4-11e6-8c8e-2ec13a2ed2e9.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19651684/4c6123aa-99e4-11e6-8241-30c4773ca06b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19651691/52889e52-99e4-11e6-8cf2-3652283aba25.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19651694/58634c8c-99e4-11e6-85c9-4ddd94daeec5.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19651703/5e123b3e-99e4-11e6-9981-0f6762cc9ba1.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19651710/64ba91a2-99e4-11e6-8b27-1ac4bcb82ad3.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19651771/98b2ee78-99e4-11e6-83b1-7c56c8ceb2a3.png)

## Sistema despliega mensaje: 
![image](https://cloud.githubusercontent.com/assets/21196249/19651898/204cda2e-99e5-11e6-9bbf-92f729a46145.png)
“Error”.

Tomaré otro Proyecto para ver como se comporta el sistema.

**Comment by felipedonoso** [comment]
**Administración:**

Al volver atrás en una revisión de SC, me envía a la bandeja de entrada:

![image](https://cloud.githubusercontent.com/assets/5757157/19658070/f6926d80-99fc-11e6-92c0-a61e4d68adea.png)

**Al pinchar me deja en la bandeja de entrada:**

![image](https://cloud.githubusercontent.com/assets/5757157/19658099/0f6bd738-99fd-11e6-9023-c58d7bd3a3af.png)

**_Debería enviarme al histórico de SC:_**

![image](https://cloud.githubusercontent.com/assets/5757157/19658140/38528bb0-99fd-11e6-864a-da7256ad0b17.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
## Rechazar Solicitud de Cambio -> Proyecto PDA FDONOSO Verificar Reporte Código 1600042189
Reporte antes de la SC
[Proyecto - 1600042189.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/548721/Proyecto.-.1600042189.pdf)

## Se revisa en Postulación

![image](https://cloud.githubusercontent.com/assets/21196249/19659923/38d20c9e-9a04-11e6-8df8-bdf62bd681c0.png)

Ahora desde URL  http://10.15.1.51/AdministracionSC/Error/Error 
## INDE 12 Administración SC QA
![image](https://cloud.githubusercontent.com/assets/21196249/19660306/93f56ac0-9a05-11e6-8638-48febc8ab82c.png)

Mensaje:
“Se ha producido un error interno. Si este persiste favor comunicarse con el Administrador. ”

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
## Se intenta nuevamente
![image](https://cloud.githubusercontent.com/assets/21196249/19660848/d73117e2-9a07-11e6-8a49-0344f9daee8a.png)

## Se filtra Proyecto por Código y Estado. 
![image](https://cloud.githubusercontent.com/assets/21196249/19660894/f5732bbe-9a07-11e6-9f68-061fe260999d.png)
Sistema trae todos los Proyectos con Estado “Aprobado / Solicitud de Cambio / En Revisión” pero no filtró por el código.
![image](https://cloud.githubusercontent.com/assets/21196249/19660953/34df9602-9a08-11e6-90f1-87afdd6de463.png)
Solicitud de Cambio.
![image](https://cloud.githubusercontent.com/assets/21196249/19661139/eeb46dd2-9a08-11e6-85b7-35fdbe202da9.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19661216/3a894002-9a09-11e6-99ae-85e3dc836b96.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19661247/5dcfa98e-9a09-11e6-8a7a-b49376651db7.png)

Se envía SC con rechazo en forma exitosa.
![image](https://cloud.githubusercontent.com/assets/21196249/19661340/b252a9a2-9a09-11e6-880c-310da96500c7.png)

Solo falta sacar el reporte Posterior a la SC rechazada.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
## Proyecto 1600042189 sacar el reporte después del Rechazo.
![image](https://cloud.githubusercontent.com/assets/21196249/19685226/e52f83d0-9a91-11e6-919f-e26fd9343783.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19685230/ebeba190-9a91-11e6-8cf8-881253cbc437.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19685235/f3cc1afc-9a91-11e6-8eef-45daea10f751.png)

## Reporte
[Proyecto - 1600042189 (1).pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/550516/Proyecto.-.1600042189.1.pdf)

## Historial de la Solicitud de Cambios
![image](https://cloud.githubusercontent.com/assets/21196249/19686249/ace4f046-9a96-11e6-91f2-a2be01cb2248.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19686279/c8bfcf98-9a96-11e6-8bd2-65582d21c082.png)
¿Por qué en el Historial de Solicitud de Cambios aparece en el Estado como ## Rechazado? Fecha 10/08/2016.-

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Rechazar una Solicitud de Cambio
Proyecto 1600042187
![image](https://cloud.githubusercontent.com/assets/21196249/19691429/a0f1997e-9aaa-11e6-9407-b011fdb876e5.png)

Sacar Reporte antes del Rechazo de la SC
![image](https://cloud.githubusercontent.com/assets/21196249/19691441/aca25f24-9aaa-11e6-9513-18f5b0b76008.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19691448/b365fe56-9aaa-11e6-8c00-202fcdaae0a7.png)
[Proyecto - 1600042187 (1).pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/550960/Proyecto.-.1600042187.1.pdf)

http://10.15.1.51/AdministracionSC
![image](https://cloud.githubusercontent.com/assets/21196249/19692280/b418fb16-9aad-11e6-885a-3a3fa21306cc.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19692285/ba490292-9aad-11e6-9d73-7ac40e58ed43.png)

## Resumen Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/19692449/58891000-9aae-11e6-92e0-e15622749ffc.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19692452/5d7a08da-9aae-11e6-8d7c-c0bd83db0f15.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19692459/628d9c2e-9aae-11e6-8649-11d2a1e0c103.png)

## Producto Original
![image](https://cloud.githubusercontent.com/assets/21196249/19692565/c097dfe6-9aae-11e6-8036-3d719c890fc0.png)

## Beneficiarios
![image](https://cloud.githubusercontent.com/assets/21196249/19694404/8d151498-9ab5-11e6-98b5-64ddb5975058.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694415/9373665a-9ab5-11e6-9ed8-0b9807cb56f6.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694422/9b097418-9ab5-11e6-8419-fc589c08b92f.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694429/a3672b28-9ab5-11e6-8e20-19a299c15d25.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694440/b2b3945e-9ab5-11e6-8734-bdb56b56072d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694443/babc0c4e-9ab5-11e6-86c7-2a3a8aa58284.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694447/bf6c7094-9ab5-11e6-91e7-7c2299812e04.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694457/c5984970-9ab5-11e6-91a5-40f080ea0dc4.png)

## Producto Solicitud
![image](https://cloud.githubusercontent.com/assets/21196249/19694472/d6b20124-9ab5-11e6-8669-884581799988.png)

## Beneficiarios
![image](https://cloud.githubusercontent.com/assets/21196249/19694550/37728916-9ab6-11e6-9c2b-6b73cbbf0e44.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694557/3c86d876-9ab6-11e6-98b2-eb4bb15f234d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694563/42beba88-9ab6-11e6-8534-d541ab329582.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694576/4a721a5e-9ab6-11e6-8d4c-1be20266073b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694580/4edd7b88-9ab6-11e6-8f93-0084b8c1e2dc.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694586/53a537e6-9ab6-11e6-8551-dea1802ae01a.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694591/594a7fee-9ab6-11e6-9e18-4504db629aca.png)


## Historial Solicitud de Cambios
Historial Solicitud de Cambios
![image](https://cloud.githubusercontent.com/assets/21196249/19694614/70e066fa-9ab6-11e6-93fe-6eef0bd599e5.png)
![image](https://cloud.githubusercontent.com/assets/21196249/19694619/76f92eb4-9ab6-11e6-9e6c-6437da7b43d6.png)

Se rechaza la Solicitud de Cambio y se saca reporte del Proyecto.

## Formulario Postulación de Proyectos Deportivos
![image](https://cloud.githubusercontent.com/assets/21196249/19694811/1ce1a9b4-9ab7-11e6-9802-23f443c708aa.png)

[Proyecto - 1600042187 (2).pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/551182/Proyecto.-.1600042187.2.pdf)

**Comment by danteghirardelli** [comment]
@felipedonoso 

Felipe,
Favor imprimir los reportes de este Proyecto 1600042187 antes y después del rechazo a la Solicitud de Cambio.
Muchas gracias.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Felipe revisé la comparación de Reportes Proyecto 1600042187 antes y después de rechazar la SC.
Mucha información está errada.
Dejé las impresiones sobre mi escritorio para que mañana las revisemos.
Saludos.

**Comment by felipedonoso** [comment]
# Conclusión:

**Se cierra esta tarea, los errores se tratarán en la siguiente tarea:**
https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/issues/34
