### ISSUE TITLE
Recuperar contraseña

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#2]
Este error no permite a un usuario el  poder recuperar la contraseña y por ende poder ingresar al sistema.

Esto es por el lado de postulación.

Revisar flujo completo, desde presionar recuperar contraseña, ingresando el capcha revisar en la Tabla Usuario en el campo "UsuContraseñaRecuperada".
También revisar el correo enviado, cambiar la contraseña entregada por una más simple:

Ejemplo: MJH56K

**Comment by felipedonoso** [comment]
@pabloespinoza, Cómo lo conversamos se implementará crear una campo en la tabla Usuario, la cuál tendrá la fecha de la solicitud, con esto el proceso que verifica la contraseña no desincriptará la fecha adjunta en la contraseña sino que la leerá de dicho campo.


Mientrás tanto estoy diseñando el mensaje al correo que nos basaremos en lo que utiliza el SII.


![captura de pantalla 2016-09-05 a las 17 20 12](https://cloud.githubusercontent.com/assets/5757157/18255834/fbf7a898-7383-11e6-8c60-968ac5ec7ddb.png)

**Comment by felipedonoso** [comment]
El formato debería ser más menos como el siguiente:

![recuperarcontrasenamail](https://cloud.githubusercontent.com/assets/5757157/18256226/c4409b08-7388-11e6-9284-c7e9607d81d7.png)

**Comment by pabloespinoza** [comment]
Los cambios están publicados en ambiente QA.

http://10.15.1.51/AltoRendimientoQA/

**Comment by pabloespinoza** [comment]
Los cambios están publicados en ambiente QA.

http://10.15.1.51/AltoRendimientoQA/

**Comment by danteghirardelli** [comment]
Se realizó la prueba de recuperación de contraseña y esta fue satisfactoria.
Adjunto evidencia.
[RecuperarContrasena_060916.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/457573/RecuperarContrasena_060916.docx)

**Comment by danteghirardelli** [comment]
Se realizó la prueba de recuperación de contraseña y esta fue satisfactoria.
Adjunto evidencia.
[RecuperarContrasena_060916.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/457575/RecuperarContrasena_060916.docx)

**Comment by felipedonoso** [comment]
@danteghirardelli por favor puedes realizar pruebas en navegadores cómo Mozilla e internet Explorer por favor.

Saludos,

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Felipe se realizó la prueba de recuperación de contraseña en navegador Mozilla.
Al presionar "Recuperar" en sección Recuperar Contraseña.
Sistema envía mensaje:
“Error al procesar la solicitud”

Por lo que no fue posible realizar la recuperación de clave.

Adjunto Evidencia.
[RecuperarContrasenaMozilla_070916.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/459073/RecuperarContrasenaMozilla_070916.docx)

**Comment by pabloespinoza** [comment]
La contraseña de la BD estaba expirada, se renueva y funciona ok.

**Comment by pabloespinoza** [comment]
La contraseña de la BD estaba expirada, se renueva y funciona ok.

**Comment by danteghirardelli** [comment]
@felipedonoso @felipedonoso 
Felipe se realizó la prueba de recuperación de contraseña en navegador Explorer y esta no fue satisfactoria.
Se  presiona "Recuperar" .
Sistema envía correctamente el mail con la nueva clave.
Se ingresa con la nueva clave NzQ3 para el Rut 16645373.
El problema es que su largo es de 4. En este punto lo normal es que sea de largo 8.
Por lo tanto cuando se intenta ingresar.

Sistema indica que  “la contraseña ingresada es incorrecta”
Adjunto documento.
[RecuperarContrasenaExplorer_070916.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/460182/RecuperarContrasenaExplorer_070916.docx)

**Comment by pabloespinoza** [comment]
Corregido, cuando se haya recuperado la contraseña no se valida el largo de esta en el inicio de sesión, favor probar nuevamente.

**Comment by pabloespinoza** [comment]
Corregido, cuando se haya recuperado la contraseña no se valida el largo de esta en el inicio de sesión, favor probar nuevamente.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

Felipe se realizó la prueba de recuperación de contraseña en navegador Explorer y esta no fue satisfactoria.
Se presiona **"Recuperar"** .
Sistema envía correctamente el mail con la nueva clave de 8 caracteres.
Se ingresa con la nueva clave **NjQ1NQ==
[RecuperarContrasenaExplorer_080916.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/461603/RecuperarContrasenaExplorer_080916.docx)
** para el Rut 16645373.
Se procede a Modificar la contraseña ingresando la clave actual, contraseña nueva y repetir la contraseña nueva.
Se presiona "Modificar" 
Sistema en sección "Modificar Contraseña" 
campo Contraseña Actual sistema indica “La contraseña ingresada no corresponde a la ingresada en el sistema”.
Esto no es correcto porque se ingresó clave “NjQ1NQ==” enviada por sistema.
Sistema me envía a sección “Modificar Contraseña” nuevamente.
Se completaron los campos solicitados( clave actual, contraseña nueva y repetir la contraseña nueva).
Se presiona "Modificar"
Nuevamente indica “La contraseña ingresada no corresponde a la ingresada en el sistema”.
No se puede realizar la acción de cambio de contraseña.

Si tiene alguna consulta me dicen.

Adjunto documento.

**Comment by pabloespinoza** [comment]
Se quitan los espacios al inicio y al final de la contraseña, en las funcionalidades de inicio de sesión y modificar contraseña.

**Comment by pabloespinoza** [comment]
Se quitan los espacios al inicio y al final de la contraseña, en las funcionalidades de inicio de sesión y modificar contraseña.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

El correo que envía el sistema con la nueva contraseña dice:

Estimada Federación: 

Usted a seleccionado la opción recuperar contraseña, la cuál por motivo de seguridad tiene un tiempo de duración de 48 Hrs. una vez terminado el plazo deberá recuperarla nuevamente. 

Recomiendo que se escriba:

Estimada Federación: 
Usted ha seleccionado la opción recuperar contraseña, la cual por motivo de seguridad tiene un tiempo de duración de 48 Hrs. 
Una vez terminado el plazo deberá recuperarla nuevamente. 
Su contraseña es la siguiente: 
OTgxNQ==

**Comment by pabloespinoza** [comment]
Correo Corregido.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Felipe se realizó la prueba de recuperación de contraseña en navegador Explorer y esta no fue satisfactoria.
Se presiona "Recuperar" .
Sistema envía correctamente el mail con la nueva clave de 8 caracteres(correo
[RecuperarContrasenaExplorer_080916v2.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/462002/RecuperarContrasenaExplorer_080916v2.docx)
 con texto corregido).
Se ingresa con la nueva clave MzQ2NQ== para el Rut 16645373.
Se procede a Modificar la contraseña ingresando la clave actual, contraseña nueva y repetir la contraseña nueva.
Se presiona "Modificar" 
Sistema nuevamente me envía a sección "Modificar Contraseña"  se ingresa la clave actual, contraseña nueva y repetir la contraseña nueva.
Se presiona "Modificar"
En campo Contraseña Actual sistema indica “La contraseña ingresada no corresponde a la ingresada en el sistema”.
Esto no es correcto porque se ingresó clave “MzQ2NQ==” enviada por sistema.
Sistema me envía a sección “Modificar Contraseña” nuevamente.
Se completaron los campos solicitados( clave actual, contraseña nueva y repetir la contraseña nueva).
Nuevamente indica “La contraseña ingresada no corresponde a la ingresada en el sistema”.
No se puede realizar la acción de cambio de contraseña.

Si tienen alguna consulta me dicen.

Adjunto documento.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Felipe se realizó la prueba de recuperación de contraseña en navegador Explorer y esta fue satisfactoria.
Se presiona "Recuperar" .
Sistema envía correctamente el mail con la nueva clave de 8 caracteres.
Se ingresa con la nueva clave ODkxNw==  para el Rut 16645373.
Se procede a Modificar la contraseña ingresando la clave actual, contraseña nueva y repetir la contraseña nueva.
Se presiona "Modificar" 
Sistema nuevamente me envía a sección "Modificar Contraseña" se ingresa la clave actual, contraseña nueva y repetir la contraseña nueva.
Se presiona "Modificar" luego se desconecta para ingresar con la Nueva Contraseña.
Es posible ingresar al Sistema con la nueva contraseña.
Con esto ya se puede pasar a Producción(se utilizaron todos los Browsers
[RecuperarContrasenaExplorer_090916v1.docx](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/463886/RecuperarContrasenaExplorer_090916v1.docx)
).

Si tienen alguna consulta me dicen.

Adjunto documento.

**Comment by felipedonoso** [comment]
@pabloespinoza Por favor generar el código necesario para pasar a producción, como lo conversamos comentar el código que se utiliza para la **Solicitudes de cambio**.

Lo otro favor de subir comprimido el archivo por esta vía, para así el lunes empezar a subir todos los cambios a esta vía antes de pasar a producción con Andy.

**Comment by felipedonoso** [comment]
Esta tarea culmino con el paso a producción, y la versión del código fue subida en el repositorio de Postulación.
