### ISSUE TITLE
Mejoras a la nueva plataforma Informática 6.- "Ícono "Recepcionar Informe"

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#20]
En conclusión: Este será un documento que se cargará desde la plataforma, en formatos: PDF, JPG,Word y Excel.

**Comment by felipedonoso** [comment]
@pabloespinoza, 

1. verificar si existe la tabla que guarde documentos relacionados al proyecto.
2. Ver si están clasificados 
3. Si permite guardar una descripción
4. Fecha de subida del documento


En la postulación y en la bandeja de entrada:

Debe estar visible por el lado de postulación que puedan subir el documento.(Tendría que ser un icono como SC).
En administración que puedan visualizar y descargar.

Diseño esto luego se pasará a un mockups:

### Administración:

![image](https://cloud.githubusercontent.com/assets/5757157/19526845/29bdc4fc-95fc-11e6-9993-6434631cd217.png)


### Postulación

![image](https://cloud.githubusercontent.com/assets/5757157/19526871/3e876e38-95fc-11e6-8812-ffd1b61ad020.png)

**Comment by pabloespinoza** [comment]
@felipedonoso la tabla Documentos_Proyecto contiene lo necesario para desarrollar lo requerido, además  en la tabla Tipo_Documento_Proyecto se creara un campo nuevo para identificar a que formulario pertenece, el contenido de esta columna sera del 20 al 29 para el formulario de informe de avance.

**Comment by pabloespinoza** [comment]
@felipedonoso Se agrega el campo dopNombreIdentificacion a la tabla Documentos_Proyecto.

**Comment by pabloespinoza** [comment]
@felipedonoso @danteghirardelli  El informe de avance en postulacion se encuentra en QA 
http://10.15.1.51/AltoRendimientoQA

**Comment by felipedonoso** [comment]
@pabloespinoza mira esto necesitaba conversar es que estaba viendo que en la parte de Administración estos documentos lo pueden visualizar como lo expreso en esta tarea:

https://github.com/InstitutoNacionalDeDeportes/AdministracionAltoRendimiento2017/issues/31

**Comment by felipedonoso** [comment]
Bien @pabloespinoza funciono perfecto lo que sí le agregaría el campo nombre del archivo, con el fin que el usuario sepa que archivo subió:

![image](https://cloud.githubusercontent.com/assets/5757157/19773457/0c43a708-9c40-11e6-8014-44e4ea807240.png)

Con esto listo lo reviso y estaría Ok y faltaría ver después por la parte de los analistas.

**Comment by felipedonoso** [comment]
@pabloespinoza estaría listo la parte de postulación, quedaría solo la parte de Administración que se visualizará en  la tarea:

#31

**Comment by felipedonoso** [comment]
**Al crear un nuevo proyecto:**

![image](https://cloud.githubusercontent.com/assets/5757157/20112232/4d21a534-a5ca-11e6-8a12-d2c675f39c71.png)

**Informe de avance:**
![image](https://cloud.githubusercontent.com/assets/5757157/20112289/8469be1e-a5ca-11e6-9a38-3edb64c76bde.png)

**Subiendo un archivo:**

![image](https://cloud.githubusercontent.com/assets/5757157/20112312/a5263736-a5ca-11e6-9fa0-caef182ca0e5.png)

**Descargando el archivo:**

![image](https://cloud.githubusercontent.com/assets/5757157/20112398/ef15acdc-a5ca-11e6-885e-41eabdf47140.png)

Subiendo un archivo "Otro":

![image](https://cloud.githubusercontent.com/assets/5757157/20112418/0fccfa7a-a5cb-11e6-97eb-0eec9de8b990.png)

**Revisando el archivo subido:**

![image](https://cloud.githubusercontent.com/assets/5757157/20112474/43aeb2b6-a5cb-11e6-8dcf-c23ab30f2c33.png)

### Revisando en Administración el proyecto 1600042196

**Comment by felipedonoso** [comment]
**Revisando en producción:**
