### ISSUE TITLE
Agregar Categoría en el Formulario de "Crear producto"

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#26]
Este atributo de categoría hace referencia para identificar las edades en que participa un deportista.

Se envía un correo a Daniela para que nos indique cuales son las categorías. 

Primero hay que revisar como a nivel de base de datos es capaz de identificar, como un deportista esta en cierta categoría.

Luego modificar el formulario de Crear producto.

**Correo enviado:**

![image](https://cloud.githubusercontent.com/assets/5757157/19981531/1565a48e-a1e1-11e6-81ff-def46b8e1188.png)

**Comment by felipedonoso** [comment]
Daniela nos responde que hay que agregar estás categorías a las ya mencionadas anteriormente:

**_Nombre categoria_**

1. No hay Deportistas 
2. Infantil
3.  Menor
4. Cadete
5.  Junior
6. Senior
7. **Sub 21**
8.  **Sub 23**
9.  **Juvenil**
10. Todo Competidor



![image](https://cloud.githubusercontent.com/assets/5757157/20007755/834c73e2-a27c-11e6-9dd6-6af575959366.png)

También se le consulto con respecto en que productos  debería aparecer y para que línea, eso se conversará, pero como primera tarea será crear la opción para todos los productos menos Administración.

**Se envió un correo también:**

![image](https://cloud.githubusercontent.com/assets/5757157/20009339/dd930fae-a282-11e6-8bdc-b547fdce2f26.png)

**Daniela nos responde lo siguiente:**

_Felipe:

Muchas gracias. El único problema, es que la categoría debe estar asociada a la actividad no al deportista, ya que un deportista que es juvenil puede participar en un evento todo competidor.
Respecto al segundo tema, efectivamente esto debe dejarse en todos los productos con excepción de administración (no asociándolo a una sola línea).

Saludos._

![image](https://cloud.githubusercontent.com/assets/5757157/20058919/5e724e9a-a4d2-11e6-944e-fcb8dc7bfec2.png)

### En conclusión:

1. Hay que agregar las categorías mencionadas anteriormente en todas las líneas, y en todos los productos **excepto el de Administración**.Será con una lista desplegable y que puedan seleccionar más de una similar a la **que presenta el gasto de viáticos**.
2. Todos los deportistas asociados al producto quedarán asociados a la categoría ingresado en el producto.

**Comment by felipedonoso** [comment]
@pabloespinoza esta es la tarea al terminar el informe de avance.

**Comment by felipedonoso** [comment]
Se realiza la consulta a Daniela por el tema de los filtros;

![image](https://cloud.githubusercontent.com/assets/5757157/20179345/71dc287a-a734-11e6-8607-9069f558594b.png)

**Comment by pabloespinoza** [comment]
@felipedonoso Este cambio se encuentra en QA y puedes verificar el resultado en la tabla CategoriaDeporte_Producto

**Comment by felipedonoso** [comment]
@pabloespinoza, como lo converse con Daniela, habrá que modificar el nombre de la Categoría:

### Todo Competidor por Adulto (Todo Competidor)

También si selecciona la opción no hay deportistas no permita agregar las demás.

Al momento de ejecutar el reporte si el producto dice:

**Categorías sub21, sub23, etc esos deportistas aparecerán en todas las categorías repitiéndose.**

**Comment by pabloespinoza** [comment]
@felipedonoso Las modificaciones se encuentran publicadas en QA y listas para su revisión.

http://10.15.1.51/AltoRendimientoQA

**Comment by felipedonoso** [comment]
Se crea un producto sin Beneficiarios:

Al seleccionar "No hay Deportistas", aparece lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/20270116/9164f4b4-aa64-11e6-8417-bf52280051e5.png)

**El producto se pudo crear:**
![image](https://cloud.githubusercontent.com/assets/5757157/20270151/ba32d24e-aa64-11e6-9197-5a0c2f85b846.png)

**Ahora seleccionando el producto de Administración:**

**No aparece la categoría, esto esta OK:**

![image](https://cloud.githubusercontent.com/assets/5757157/20270181/e7255114-aa64-11e6-84f1-804751eafca4.png)

**Agregando todas las categorías:**

![image](https://cloud.githubusercontent.com/assets/5757157/20270287/415296ec-aa65-11e6-99e0-23a856c2ffdb.png)

**Agregando de una en una:**

**Infantil**
![image](https://cloud.githubusercontent.com/assets/5757157/20270361/83f60394-aa65-11e6-959e-8a6ae61cbb02.png)

Se edita las categorías:

![image](https://cloud.githubusercontent.com/assets/5757157/20270382/99e9f174-aa65-11e6-9017-0c7d2dfc5554.png)

Cadete:
![image](https://cloud.githubusercontent.com/assets/5757157/20270404/afd5ad52-aa65-11e6-8d95-a4f1f96f8eb7.png)

**Junior / Senio:**

![image](https://cloud.githubusercontent.com/assets/5757157/20270484/fdc0c178-aa65-11e6-90b3-6ef6aedb0b43.png)

El resto de las actividades:

![image](https://cloud.githubusercontent.com/assets/5757157/20270505/1a4edb86-aa66-11e6-9cc6-b4c8a8a33a2c.png)


### Conclusión:

@pabloespinoza hay que agregar la opción **"Todas"**  para agilizar el ingreso. 
Lo demás esta OK.

Lo otro  ¿como puedo verificar en la Base de datos que el deportista esta asociado a la categoría seleccionada en el producto?

**Comment by pabloespinoza** [comment]
@felipedonoso El cambio solicitado se encuentra en QA y la tabla para ver los resultados es "CategoriaDeporte_Producto"

**Comment by felipedonoso** [comment]
### Proyecto de prueba: 1600042196	PROYECTO DE PRUEBA TIPO GASTO
**Primero se creará un producto con todas las categorías:**

La idea es ver en la base de datos como queda registrado un producto que por error el usuario agrego una categoría en este caso **"Cadete"** y luego selecciono **"Todas"**

![image](https://cloud.githubusercontent.com/assets/5757157/20304527/76ca74ac-ab0f-11e6-8e6c-27a642d991e6.png)

**Al editar no aparece en la lista la opción "Todas":**

![image](https://cloud.githubusercontent.com/assets/5757157/20304868/3cea6682-ab11-11e6-8146-2faf24167ac3.png)


**Ahora crearemos un nuevo producto solo ingresando la opción "Todas":**

![image](https://cloud.githubusercontent.com/assets/5757157/20304976/d6d94466-ab11-11e6-9d1e-011cad7051b2.png)

**Este es el deportista:**
![image](https://cloud.githubusercontent.com/assets/5757157/20305084/73f008b6-ab12-11e6-8316-3f5f791ff52b.png)

**Revisando en la tabla: "CategoriaDeporte_Producto"**

![image](https://cloud.githubusercontent.com/assets/5757157/20305337/cf8c2e7e-ab13-11e6-8545-bd7bc0417661.png)

Y estoy tratando de saber como llego al Deportista, al revisar en la tabla: **categoria_deporte**

![image](https://cloud.githubusercontent.com/assets/5757157/20305408/3e520f72-ab14-11e6-8148-707b1a20675f.png)

El formulario valida que ingrese una categoría para el **producto:**

![image](https://cloud.githubusercontent.com/assets/5757157/20305680/75f94f48-ab15-11e6-9e7b-a8a50eda87f9.png)


## Resumiendo:
### ¿Como llego al Deportista desde la tabla CategoriaDeporte_Producto?
Cuando una persona presiona una opción y luego selecciona "Todas" al Editar no me aparece ninguna seleccionada, pensé que podría salir todas seleccionadas o la primera que escogió.

**Comment by felipedonoso** [comment]
Revisando :+1: 
![image](https://cloud.githubusercontent.com/assets/5757157/20306617/fdf06888-ab19-11e6-98ff-9bd68bfecd44.png)


**El cual coincide con lo registrado anteriormente:**

![image](https://cloud.githubusercontent.com/assets/5757157/20305084/73f008b6-ab12-11e6-8316-3f5f791ff52b.png)

### Sólo quedaría resolver el caso que mencione anteriormente:

Cuando una persona presiona una opción y luego selecciona "Todas" al Editar no me aparece ninguna seleccionada, pensé que podría salir todas seleccionadas o la primera que escogió.

**Comment by felipedonoso** [comment]
Se vuelve a realizar la prueba:

![image](https://cloud.githubusercontent.com/assets/5757157/20307487/737ff420-ab1e-11e6-85ed-ff59ff93c279.png)

Luego se edita:

![image](https://cloud.githubusercontent.com/assets/5757157/20307533/a0e7d95a-ab1e-11e6-9946-bc7a72ca75af.png)

@pabloespinoza generar el código para pasar a producción y poder hacer la revisión para cerrar esta tarea.

**Comment by pabloespinoza** [comment]
@felipedonoso Modificación publicada en QA.

**Comment by felipedonoso** [comment]
@pabloespinoza al conversar con Daniela, se llego al acuerdo de que cuando un producto se crea y se selecciona "No hay Deportistas" en la opción Categoría, y el postulante agrega un nuevo beneficiario con el cargo **"Deportista"** al presionar **"grabar"** deberá indicarle:

### El producto no contempla "Deportistas", favor de modificar el producto en su categoría

**Comment by pabloespinoza** [comment]
@felipedonoso Se modifica y se publica en QA.

**Comment by felipedonoso** [comment]
**Se crea el producto:**
![image](https://cloud.githubusercontent.com/assets/5757157/20361235/9bfc67e2-ac15-11e6-8d40-75085c15d846.png)

**Agregando un Beneficiario Deportista:**
![image](https://cloud.githubusercontent.com/assets/5757157/20361309/e9f034f6-ac15-11e6-8d11-d46c370e51bc.png)

### NOTA: Agregar acento a la palabra Asignación.

**Se modifica la categoría:**

![image](https://cloud.githubusercontent.com/assets/5757157/20361416/3bcf8074-ac16-11e6-8498-df7983e1b344.png)


**Se agregará nuevamente al deportista:**

![image](https://cloud.githubusercontent.com/assets/5757157/20362660/3212c686-ac1b-11e6-837b-5ea58a3e1a51.png)

**Color del header donde están los link:  #3C454F**

@pabloespinoza favor de generar el código necesario para pasar a produccióny  hacer la revisión en producción

**Comment by felipedonoso** [comment]
**Se pasa a producción y estos son los archivos modificados:**

`	modified:   Models/ModeloAltoRendimiento.edmx.diagram
	modified:   Views/AntecedenteGeneralProyecto/Index.cshtml
	modified:   Views/AsignarBeneficiarios/_Create.cshtml
	modified:   Views/Home/InicioSesion.cshtml
	modified:   Views/Producto/Index.cshtml
	modified:   Views/Producto/_Create.cshtml
	modified:   Views/Producto/_Edit.cshtml
	deleted:    Views/ProductoCopia/Create.cshtml
	deleted:    Views/ProductoCopia/Delete.cshtml
	deleted:    Views/ProductoCopia/Details.cshtml
	modified:   Views/Shared/_Layout.cshtml
	deleted:    Web References/WSConverge/Reference.map
	modified:   bin/AltoRendimiento.XmlSerializers.dll
	modified:   bin/AltoRendimiento.dll
	deleted:    css/Thumbs.db`
![image](https://cloud.githubusercontent.com/assets/5757157/20393156/8b7dd186-acb9-11e6-94e4-3d1aa09cba8f.png)

**Se revisa en Producción:**

Bandeja de entrada:
![image](https://cloud.githubusercontent.com/assets/5757157/20393238/d3b337ac-acb9-11e6-95d6-a69a7d138d67.png)

**Categoría en el producto:**

![image](https://cloud.githubusercontent.com/assets/5757157/20393271/fbec4a60-acb9-11e6-86fa-b652e8d00f0b.png)

**Producto creado:**
![image](https://cloud.githubusercontent.com/assets/5757157/20393305/248d0bb2-acba-11e6-903f-13b5213e2cab.png)

**Deportista Agregado:**
![image](https://cloud.githubusercontent.com/assets/5757157/20393326/4639e9f6-acba-11e6-89b2-41ba3cb0d007.png)

**_Al modificar un producto con Beneficiarios Deportistas, esto ocurre cuando le asignas categoría y luego al editar el producto._**

![image](https://cloud.githubusercontent.com/assets/5757157/20393376/7e179f1c-acba-11e6-8bf4-04e48076ee4d.png)

**Creando un producto sin Beneficiarios:**

![image](https://cloud.githubusercontent.com/assets/5757157/20393438/b71591ca-acba-11e6-9f8d-a944349a246a.png)


**Agregando un Deportista, en un producto que no contempla dicho cargo:**

![image](https://cloud.githubusercontent.com/assets/5757157/20393493/e2f3ad5e-acba-11e6-8d9b-b53b0731b111.png)


### Ahora revisando en la Base de datos:

![image](https://cloud.githubusercontent.com/assets/5757157/20393940/90e582f6-acbc-11e6-9aab-a68f1b72162d.png)

# La revisión concluye con éxito en la base de datos se cierra esta tarea:
