### ISSUE TITLE
Validación Diseño Plurianual

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#35]
Se validará que al momento de leer el concurso Vigente, exista al menos un diseño anual mayor o igual al año del concurso.

Esta es una regla invalidante, gracias Pablo por detectarlo.

**Comment by felipedonoso** [comment]
Se revisará el icono (Subir informe de avance) de una tarea anterior, y el diseño plurianual.

**En estado incompleto:**

![image](https://cloud.githubusercontent.com/assets/5757157/21656451/f941b4b8-d29c-11e6-8a08-3d09c95eb3f6.png)

**Al filtrar por estado postulado:**
![image](https://cloud.githubusercontent.com/assets/5757157/21656607/a9aa1cd2-d29d-11e6-9055-9d63902ca378.png)

**Al filtrar por Pre-Seleccionado:**
![image](https://cloud.githubusercontent.com/assets/5757157/21656674/dc4bb72c-d29d-11e6-9c20-55729ec6b4e3.png)

 Objetado:
![image](https://cloud.githubusercontent.com/assets/5757157/21656703/f91dd452-d29d-11e6-9e9e-5e6642193071.png)

Seleccionado:
![image](https://cloud.githubusercontent.com/assets/5757157/21656764/34808846-d29e-11e6-8c82-ab2179ab7927.png)

Aprobado:
![image](https://cloud.githubusercontent.com/assets/5757157/21656806/58dd4ab2-d29e-11e6-939d-bec9bac623c4.png)

**Observación: Aparece el icono "Solicitud de Cambio".**


### Revisión Plurianual:

Se eliminará el año 2016, con lo cual no le permitirá crear un proyecto del concurso del mismo año.
![image](https://cloud.githubusercontent.com/assets/5757157/21656880/b6b7daf8-d29e-11e6-89a4-937b601b1ffd.png)

No se pudo eliminar el diseño plurianual, el modal que se presenta no se puede visualizar en su totalidad, es posible dejar este modal que se presente como encima en la página y que esta quede en  background.
![image](https://cloud.githubusercontent.com/assets/5757157/21679130/0a685db2-d321-11e6-8e00-2996bb5d010e.png)


**Debe ser algo similar a esta página:**
![image](https://cloud.githubusercontent.com/assets/5757157/21679106/e8501170-d320-11e6-8da8-05809ba5bce2.png)

O mostrar el contenido en formato mas ancho pero que se permita poder  ver el contenido.

# Conclusión:

1. Al filtrar por los estados del proyecto el icono Subir informe de avance esta OK.
2. Al eliminar un registro del diseño plurianual, el modal no da las facilidades para poder eliminar el registro he inhabilita la acción.

**Comment by pabloespinoza** [comment]
@felipedonoso Se encuentra corregido y publicado en QA.

**Comment by felipedonoso** [comment]
**Eliminando el Diseño plurianual:**
![image](https://cloud.githubusercontent.com/assets/5757157/21685868/f1f9824e-d341-11e6-8f1d-530ffdf6f724.png)

**Presentación:**
![image](https://cloud.githubusercontent.com/assets/5757157/21685930/302929b6-d342-11e6-86b7-bdad3ed064bb.png)

**Pablo, favor de dejar un mensaje como aparece en el título ¿Esta seguro que desea eliminar este registro? y agregar los botones Sí o No.**

Gracias

**Comment by pabloespinoza** [comment]
@felipedonoso Publicado en QA.

**Comment by felipedonoso** [comment]
**Eliminando un registro del Plurianual:**
![image](https://cloud.githubusercontent.com/assets/5757157/21693572/2ff33dd8-d360-11e6-8d18-c17b6fd0f807.png)

**Ahora se intentará crear un proyecto, el cual no debe permitirlo.**
![image](https://cloud.githubusercontent.com/assets/5757157/21693691/a2def972-d360-11e6-9a60-57391614f247.png)

@pabloespinoza elimine el único registro del Diseño plurianual:
![image](https://cloud.githubusercontent.com/assets/5757157/21693721/c8787ffa-d360-11e6-9649-bb25e2a2f31e.png)


Como lo habíamos conversado si existe un registro del diseño plurianual >= al año de concurso Vigente, debe poder crearse, de no ser así no debe permitir crear dicho proyecto e indicar a la federación que debe crearlo.

**Comment by felipedonoso** [comment]
**Se  revisará al momento de postular el proyecto que indique que debe rellenar el diseño plurianual:**

![image](https://cloud.githubusercontent.com/assets/5757157/21719623/753e466a-d3fd-11e6-8a55-092fccd9bb6a.png)

La duda que tengo que me aparece es, ¿El botón postular no debería estar? o ¿por motivos de validación se oculta? de ser así habría que cambiarlo para que aparezca el botón y que al presionar envíe el mensaje.

Esto por qué el usuario llamará indicando **"No me aparece el botón postular"** .

**Comment by pabloespinoza** [comment]
@felipedonoso Cambio publicado en QA.

**Comment by felipedonoso** [comment]
### Al crear el proyecto y postularlo sin tener el diseño plurianual:
![image](https://cloud.githubusercontent.com/assets/5757157/22020198/c674d472-dc95-11e6-9a60-45ef016dc239.png)

_Diseño Creado:_
![image](https://cloud.githubusercontent.com/assets/5757157/22020665/3261b32e-dc98-11e6-9045-8287dcca8f5a.png)

Verificar y postular:
![image](https://cloud.githubusercontent.com/assets/5757157/22020678/54e59f82-dc98-11e6-99fb-c2afd7aca92b.png)

**Se sube un documento:**
![image](https://cloud.githubusercontent.com/assets/5757157/22020716/82c6d858-dc98-11e6-99db-dad7c21146d1.png)

**Al revisar en la bandeja de administración:**

![image](https://cloud.githubusercontent.com/assets/5757157/22020864/2f1723ce-dc99-11e6-88ce-8d5bd807cfe8.png)

**Al postularlo y luego al realizar los filtros:**
![image](https://cloud.githubusercontent.com/assets/5757157/22020937/7f4d8ffe-dc99-11e6-9d00-637951ea8186.png)

# Conclusión:

1. El diseño plurianual esta bien, solamente la sugerencia sería al momento de filtrar me aparece un código 1600042197 y en el filtro seleccione proyectos año 2017 postulados.
2. Esta listo para pasarse a producción

**Comment by felipedonoso** [comment]
Al revisar en producción funciono OK

Agregando TEXTO

![image](https://cloud.githubusercontent.com/assets/5757157/22221874/7583b01c-e193-11e6-9f8d-2adec9b941c3.png)

Modificando:
![image](https://cloud.githubusercontent.com/assets/5757157/22221927/b17366c6-e193-11e6-91b5-08cb860ce574.png)

Esta OK

**Comment by felipedonoso** [comment]
Al presionar el verificar y postular valida que este registro al menos tenga uno.

# CONCLUSIÓN:

**A quedado correcto.**
