### ISSUE TITLE
Habilitación mes de enero para las Federaciones de Boxeo y Billar

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#41]
@pabloespinoza, como lo conversamos habría que habilitar a estas 02 federaciones para que puedan postular un proyecto por la línea de administración:**Art. 1º ley 19135 Fed. Dep. Nacional**, SOLAMENTE PARA ESTA LINEA.

**Comment by pabloespinoza** [comment]
@felipedonoso ya se puede probar en QA.

**Comment by felipedonoso** [comment]
La primera prueba se realizará con el rut que tenemos de prueba **16645373**, que esta asociado a la federación: **Boxeo**.

PROYECTO CREADO CON **ÉXITO:**
![image](https://cloud.githubusercontent.com/assets/5757157/24663418/3d662034-192e-11e7-8b8b-c8c47b71795f.png)

PRODUCTO CREADO CON **ÉXITO:**
![image](https://cloud.githubusercontent.com/assets/5757157/24664098/1fa6a940-1930-11e7-887e-8e69c33a965a.png)

**AHORA CON BILLAR:**

![image](https://cloud.githubusercontent.com/assets/5757157/24664271/9e64401c-1930-11e7-91c6-c9a9ed1faf18.png)

**PRODUCTO BILLAR PDA:**

![image](https://cloud.githubusercontent.com/assets/5757157/24664377/e2224a1a-1930-11e7-9ed8-35f46debd026.png)

**AHORA REVISANDO CON OTRA FEDERACIÓN:**

![image](https://cloud.githubusercontent.com/assets/5757157/24664460/186a059a-1931-11e7-8db2-5c4904dfd29e.png)


@pabloespinoza, FAVOR DE PASAR SOLO LAS PIEZAS DE ESTE CAMBIO QUIERO REVISAR EN LA TARDE EL NUEVO FLUJO PARA CONFIRMAR QUE TODO ESTA IMPEQUE.

**Comment by felipedonoso** [comment]
Se verificará en producción BOXEO:

![image](https://cloud.githubusercontent.com/assets/5757157/24806263/aac628d2-1b8a-11e7-9d64-7f99c5d10e5b.png)

![image](https://cloud.githubusercontent.com/assets/5757157/24806281/b83f5dbc-1b8a-11e7-9935-1ee2640e71a4.png)

Al eliminar el proyecto de **prueba:**
![image](https://cloud.githubusercontent.com/assets/5757157/24806362/fafa86ae-1b8a-11e7-8ec1-75b71847d68d.png)


**BILLAR**:

![image](https://cloud.githubusercontent.com/assets/5757157/24806421/327eb474-1b8b-11e7-811c-e60ec9569108.png)


Creando el proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/24806458/55284a4e-1b8b-11e7-97c0-4d4c51b7954a.png)
