### ISSUE TITLE
Editar proyecto

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#42]
Se revisará que al momento de Editar un proyecto solo sea posible en los  siguientes estados:

1. Incompleto
2. Ingresado
3. Objetado

**Comment by felipedonoso** [comment]
@danteghirardelli puedes hacer la prueba con los proyectos en estado **"INCOMPELTOS".**

**Comment by felipedonoso** [comment]
### Proyectos incompletos:

![image](https://cloud.githubusercontent.com/assets/5757157/26421980/19c76fc2-4096-11e7-8ad6-aff00caa4724.png)

Proyecto Original:

![image](https://cloud.githubusercontent.com/assets/5757157/26422013/30180d36-4096-11e7-948e-bf287a5f0ceb.png)

MODIFICANDO:
![image](https://cloud.githubusercontent.com/assets/5757157/26422091/77edf954-4096-11e7-8272-4c58093fe3b1.png)

Al consultar en la Bandeja de entrada:
![image](https://cloud.githubusercontent.com/assets/5757157/26422116/883d50a2-4096-11e7-9aaa-88a01ab64411.png)

**Comment by felipedonoso** [comment]
Al editar el proyecto **1700042018**

Los campos se pueden editar, lo cuál esta correcto, ahora se modificará los meses de inicio y fin:

![image](https://cloud.githubusercontent.com/assets/5757157/26452100/a374366a-412c-11e7-8aa8-673a3f9ee35c.png)

Ahora al editar el mes de inicio de Enero a **Febrero**:

![image](https://cloud.githubusercontent.com/assets/5757157/26452165/efd36300-412c-11e7-9ac5-ba8d570b81b6.png)

Cambiando la Región: Nivel Nacional a Antofagasta:

![image](https://cloud.githubusercontent.com/assets/5757157/26452227/32a3d0ca-412d-11e7-85f9-bf7ba4633bfa.png)

### El estado Incompleto esta OK

**Comment by danteghirardelli** [comment]
## Prueba Editar nombre Proyecto en estado “Incompleto” 
Proyecto  !"#$%&/()=?¡?==?=)(/&%-+/*ABCDE 
![image](https://cloud.githubusercontent.com/assets/21196249/26452839/72f46430-412f-11e7-8f27-ba3eb671ccc3.png)
![image](https://cloud.githubusercontent.com/assets/21196249/26452842/77241618-412f-11e7-96fe-06ec4db34d00.png)
Se modifica Nombre Proyecto.
![image](https://cloud.githubusercontent.com/assets/21196249/26452851/82a0ff6a-412f-11e7-9351-f381052c30c4.png)

## Se filtra Proyecto por Incompleto
![image](https://cloud.githubusercontent.com/assets/21196249/26452879/9bed81b4-412f-11e7-81bc-c082011a5208.png)
No realiza el refresh instantáneo con el cambio realizado.
Proyecto ahora aparece con nombre “Cambio Nombre 250517”.

En resumen permite realizar el cambio de nombre de un proyecto en estado "Incompleto"
@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
Revisando el estado Ingresado:  Este es el que presenta el problema, cuando el ANALISTA, Observa un proyecto, el botón **_Observar_** funciona el equivalente al botón **Objetar**.

Entonces si la Federación ingresa el proyecto, y el analista realiza la observación, vuelve al postulante el cual podrá modificar el proyecto según lo solicitado:

Acá se puede apreciar que 02 proyectos, con el mismo estado **"INGRESADO"**

![image](https://cloud.githubusercontent.com/assets/5757157/26452356/ae25ce6a-412d-11e7-8c53-830dceae03ea.png)

Ingresado, enviado al ANALISTA: The King 23

**El mensaje fue ALexis le pega al KING.**

Ahora se puede apreciar que el proyecto, tiene la opción **_Verificar y postular._**

![image](https://cloud.githubusercontent.com/assets/5757157/26453058/60cda16c-4130-11e7-9770-e20090cde1ac.png)

Al modificar el proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/26453080/7d2fe806-4130-11e7-9d2c-f4b29cb2a828.png)

Al modificar el Nombre del proyecto y se presiona el botón GUARDAR, reclama por el mes de INICIO, se visualiza previo a esto que el mes de inicio no lo entrega.

El error es que al momento de GUARDAR, aparece la alerta pero debe permitir modificar o que el botón GUARDAR, no desaparezca y que no bloquee todo.

**Comment by danteghirardelli** [comment]
## Prueba Editar nombre Proyecto en estado “Objetado”
Proyecto  Plurianual 3 FDONOSO  Código # 1700042030
![image](https://cloud.githubusercontent.com/assets/21196249/26456295/a3803f38-413a-11e7-9636-e4da86458305.png)
![image](https://cloud.githubusercontent.com/assets/21196249/26456298/a7ec1e98-413a-11e7-8b40-72a5e1e345c7.png)
Editar Nombre Proyecto
![image](https://cloud.githubusercontent.com/assets/21196249/26456323/b496ee98-413a-11e7-944f-16d1522ed55d.png)
Desaparece Mes Inicio
![image](https://cloud.githubusercontent.com/assets/21196249/26456333/bf821e86-413a-11e7-9812-12676bb3a3b9.png)

Al presionar “Guardar” 
![image](https://cloud.githubusercontent.com/assets/21196249/26456353/c9958976-413a-11e7-9dcc-7ed4041fef5a.png)
Envía mensaje correcto y no permite realizar el cambio.

Problema ya fue detectado por ustedes.
@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
Se modificará el proyecto:

**_Proyecto para revisar gastos MATERIALES DE OFICINA Y ENSEÑANZA y PUBLICACIONES E IMPRESOS_**

![image](https://cloud.githubusercontent.com/assets/5757157/26458059/3a6a7cce-4140-11e7-84dc-db2a4babb845.png)

El campo que valida el estado Ingresado se encuentra en 3:
![image](https://cloud.githubusercontent.com/assets/5757157/26458224/a46dcc34-4140-11e7-9143-334453969ad2.png)


Utilizaremos otro proyecto:

**_CambioCargo_050517_**

Se encuentra en estado=2
![image](https://cloud.githubusercontent.com/assets/5757157/26458294/cbbaaf50-4140-11e7-90a5-d039cdc6ccd3.png)

Ahora aparece el botón GAURDAR, después de modificar el mes de inicio:

![image](https://cloud.githubusercontent.com/assets/5757157/26458377/0baeb07a-4141-11e7-862a-24777bcb15d3.png)

![image](https://cloud.githubusercontent.com/assets/5757157/26458410/2b8bfb78-4141-11e7-8101-e407b7b2387b.png)

Al modificar el nombre y la región se pueden apreciar los cambios:

Ahora:

![image](https://cloud.githubusercontent.com/assets/5757157/26458425/3669d5a6-4141-11e7-84c8-04a9ad989eab.png)

**Comment by felipedonoso** [comment]
### Se volverá a INGRESAR PARA SU POSTULACIÓN:

**SE PUEDE VISUALIZAR LA OBSERVACIÓN:**

![image](https://cloud.githubusercontent.com/assets/5757157/26458496/6bc24f80-4141-11e7-8f3b-85769a39f951.png)

Desaparece el icono "Verificar y postular", ya se encuentra en las manos del analista.
![image](https://cloud.githubusercontent.com/assets/5757157/26458577/a7d4019e-4141-11e7-9fd8-9dce46f5982b.png)

**ACEPTAR PROYECTO:**

![image](https://cloud.githubusercontent.com/assets/5757157/26458632/d3090a30-4141-11e7-9c52-9fc4e9ea8b8f.png)

EN LA BANDEJA DE ENTRADA DE POSTULACIÓN: **Vuelve aparecer el icono "Verificar y postular"**

![image](https://cloud.githubusercontent.com/assets/5757157/26458681/f3381594-4141-11e7-8aba-e4fa33a31f22.png)

POSTULANDO EL PROYECTO:

![image](https://cloud.githubusercontent.com/assets/5757157/26458731/1c3048a4-4142-11e7-8d1b-8b05f33f50d7.png)

VERIFICANDO EN LA TABLA:

![image](https://cloud.githubusercontent.com/assets/5757157/26458781/43924f64-4142-11e7-9889-625bec08e641.png)


# CONCLUSIÓN:

Para el estado "INGRESADO", hay 03 etapas:

1.- Primera vez que se envía el proyecto .
2.- Revisión del analista.
3.- De ser aceptado el proyecto, queda listo para la postulación, en caso contrario se podrá volver a ingresar.

**Comment by felipedonoso** [comment]
Se objetará el mismo proyecto: 1700042038

**_CambioCargo_050517 cambio nombre y mes a junio_**

Objetando:
![image](https://cloud.githubusercontent.com/assets/5757157/26458922/bbf9106e-4142-11e7-8281-31fb83aa97d9.png)

Se modificar el nombre del proyecto: Se vuelve a dejar como estaba:

ANTES:
![image](https://cloud.githubusercontent.com/assets/5757157/26459154/8cd57380-4143-11e7-88bc-5060ddcd89a4.png)

DESPUÉS:

![image](https://cloud.githubusercontent.com/assets/5757157/26459179/9bd67fa0-4143-11e7-842c-00ae4ae1d5e7.png)

SE VUELVE A POSTULAR:

![image](https://cloud.githubusercontent.com/assets/5757157/26459231/bf00936c-4143-11e7-9996-3ec8a4823810.png)

**Comment by felipedonoso** [comment]
Se pudo postular:

![image](https://cloud.githubusercontent.com/assets/5757157/26467426/85924a2c-4160-11e7-94fb-2a5ae9dcba4f.png)

**Comment by felipedonoso** [comment]
# Conclusión: 
**Esto se encuentra solucionado en producción.**
