### ISSUE TITLE
<Fiscalización- Carolina Boado> <Agregar competencia> <Diseño>

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#60]
Se modificará el formulario, se agregará la opción de agregar competencias:

**El diseño debería ser el siguiente:**

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/2475fe72-f16f-4f7a-9106-27f233e4307d)

Se podrán ingresar de 1 a N competencias dentro del mismo formulario y deberá expandirse a medida crece el número de competencias.

## Paso 1:

![image](https://user-images.githubusercontent.com/5757157/36421435-2bdf9bd8-1617-11e8-9e3c-3f654650870e.png)

## Paso 2:

![image](https://user-images.githubusercontent.com/5757157/36421475-51e76ed2-1617-11e8-8c58-a02fbc581c44.png)

**Comment by felipedonoso** [comment]
**El prototipo se puede apreciar en el siguiente enlace:**

Ver online:
https://drive.google.com/file/d/1GoqXQGGf63X9_80YGj_XCiPBa4uS5M-6/view?usp=sharing

**Comment by felipedonoso** [comment]
### Dudas:

**Esta opción estará para todos los productos?**
**Esto tomará una SC, si desean modificar la fecha de un producto?**

**Comment by felipedonoso** [comment]
# Resumen:

### Paso 1:

![image](https://user-images.githubusercontent.com/5757157/36670778-0f24a770-1ad8-11e8-99a7-ae671e1640a0.png)


### Paso 2:

![image](https://user-images.githubusercontent.com/5757157/36670699-d4a63dd4-1ad7-11e8-82bb-bf716e90811f.png)

### Ver mapa:

![image](https://user-images.githubusercontent.com/5757157/36670747-f6e56dfc-1ad7-11e8-9e45-313a8cb500c9.png)

# Desafíos:

Como desafío sería ideal utilizar la **API de google para el calendario**, con esto los usuarios que tengan cuenta en Google podrán tener una alerta en su dispositivo Android u iphone.

![image](https://user-images.githubusercontent.com/5757157/36671285-d1ca2452-1ad9-11e8-9e9b-bae4b4ce6dea.png)

**Comment by pabloespinoza** [comment]
El campo N° de la grilla se obtendrá de la tabla Competencia al igual que el resto de las columnas.

**Comment by pabloespinoza** [comment]
En la grilla, en ves de Producto dira Competencia y corresponde al nombre de la competencia.

**Comment by pabloespinoza** [comment]
Productos que deben tener competencias, se definen que los siguientes productos tendrán que ingresar competencias de manera obligatoria y que tengan nivel nacional:

    Entrenamiento y concentraciones
    Organización de competencias
    Participación en competencias
    Capacitaciones

**Comment by felipedonoso** [comment]
Como lo comentamos el icono debería cambiarse en vez de un icono de GPS o geolocalización debería ser uno de competencia por ejemplo :

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/e9b548be-fd18-4d3f-a0f7-55d42a2d5538)

**Comment by felipedonoso** [comment]
@pabloespinoza   la validación en la parte de **"Verificar y postular"** se considerará como una mejora a la entrega del **SPRINT 2**, sería un **RELEASE** para esta tarea.

**Comment by felipedonoso** [comment]
Esta tarea esta validad por la revisión de QA:

https://app.zenhub.com/workspace/o/institutonacionaldedeportes/postulacionaltorendimiento2017/issues/61

Se cierra la tarea

**Comment by felipedonoso** [comment]
Se pasa a producción y se puede observar el icono en los productos:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/70b16e0a-fe66-45fd-adf8-3fa57c8392f1)

Se puede ver el listado  de las competencias:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/a30828ba-c990-43c1-913a-dc9da5f78fcd)

Se ingresa la competencia:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/6d82ca89-766d-4a53-948d-da81712f1a75)

Y tiene validaciones en las fechas:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/801d01b7-8bb4-42ae-9a1e-2b4bbe7097b6)

Competencia Creada:

[Uploading... image.png ]

**Comment by felipedonoso** [comment]
Commit asociado:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/8c618938-4027-4e6a-8746-09f69515acb8)

Se agrega el código del Reporte:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/188d1fb7-fa8e-470e-8416-1f5684cc4c8d)

**Comment by felipedonoso** [comment]
**Revisando el reporte:**

LA COMPETENCIA PERTENECE AL PRODUCTO 2:

![image](https://user-images.githubusercontent.com/5757157/39304504-4783ef0a-4930-11e8-9450-c93bc75b2105.png)

REVISANDO EL REPORTE:

![image](https://user-images.githubusercontent.com/5757157/39304619-9804dfa2-4930-11e8-998b-ae4047f33858.png)

COMPETENCIA:

![image](https://user-images.githubusercontent.com/5757157/39304634-ab799226-4930-11e8-945b-735fa0e0e940.png)

# CONCLUSIÓN:

**Se da por terminado la tarea de competencias.**
