### ISSUE TITLE
<QA Agregar competencia> <QA Reporte>

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#65]
### Esta tarea consiste en revisar las competencias agregadas en el sistema de postulación.

Se debe validar el reporte del proyecto en la sección de producto.
Se debe validar en el sistema de administración.

**Credenciales:**

http://10.15.1.51/AdministracionQA
RUT:153149682
Clave:Nov0915,

http://10.15.1.51/AltoRendimientoQA
RUT:16645373
Clave: federacion2016 14152301K

**Comment by felipedonoso** [comment]
# Revisión postulación:


### Proyecto:

![image](https://user-images.githubusercontent.com/5757157/37596214-3d4db47e-2b5a-11e8-8c13-2e09e7e4dee7.png)

### Productos con competencia:

![image](https://user-images.githubusercontent.com/5757157/37596189-22d46be2-2b5a-11e8-8afc-94155779cb49.png)

**Producto 3:**

![image](https://user-images.githubusercontent.com/5757157/37596359-afc015e2-2b5a-11e8-807d-9bd43fc42e3f.png)

**Producto 4:**

![image](https://user-images.githubusercontent.com/5757157/37596403-d1485c4c-2b5a-11e8-8113-7f164779ecf7.png)

**Producto 5:**

![image](https://user-images.githubusercontent.com/5757157/37596443-f1209c00-2b5a-11e8-8eca-925086a990e7.png)

**Producto 6:**

![image](https://user-images.githubusercontent.com/5757157/37596475-06625e5a-2b5b-11e8-8b80-11323cfd664f.png)

Se observa en la sección de Detalle:

**Producto 3:**

![image](https://user-images.githubusercontent.com/5757157/37596576-66231050-2b5b-11e8-86ae-06009965ea2e.png)

**Producto 4:**

![image](https://user-images.githubusercontent.com/5757157/37596665-ad4381cc-2b5b-11e8-880a-63137ab96f72.png)

**Producto 5:**

![image](https://user-images.githubusercontent.com/5757157/37596696-c8daf96a-2b5b-11e8-8baf-605eeb8cb8f2.png)

**Producto 6:**

![image](https://user-images.githubusercontent.com/5757157/37596731-df7b9558-2b5b-11e8-9971-4deb4efb7180.png)


## Conclusión:

**@danteghirardelli, favor de verificar en la descripción y que coincidan con lo ingresado en el producto por favor y como te mencione todo esto se observa en la parte de detalle del producto 3,4,5 y 6.**

**Comment by felipedonoso** [comment]
## Revisión Administración:

**Proyecto:** 

![image](https://user-images.githubusercontent.com/5757157/37597809-31fcd384-2b5f-11e8-9a30-916e175b18d8.png)

**ERROR:**

![image](https://user-images.githubusercontent.com/5757157/37597953-9aebd96c-2b5f-11e8-8244-92abfc77391c.png)

## Conclusión:

La tarea llega hasta acá, no fue posible continuar.

**Comment by danteghirardelli** [comment]
Se revisarán y compararán las Competencias agregadas para el Proyecto "Agregar competencia". 
http://10.15.1.51/AltoRendimientoQA
RUT:16645373
Clave: federacion2016

![image](https://user-images.githubusercontent.com/21196249/37594929-8e231718-2b55-11e8-9e12-9fdf2a0377a4.png)
![image](https://user-images.githubusercontent.com/21196249/37594938-9886517a-2b55-11e8-9285-4dd17e276eca.png)
![image](https://user-images.githubusercontent.com/21196249/37595191-a4acb6aa-2b56-11e8-96b0-7df7f13b67aa.png)
Al presionar Exportar PDF sistema envío un mensaje de error por demora en la respuesta.

[Proyecto - 0 (4).pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/1825109/Proyecto.-.0.4.pdf)

Se ingresa nuevamente y ahora carga "Formulario Postulación de Proyectos Deportivos".
![image](https://user-images.githubusercontent.com/21196249/37595490-c27dee3c-2b57-11e8-94f0-ec2f80893a89.png)

![image](https://user-images.githubusercontent.com/21196249/37595411-7f141702-2b57-11e8-9bfb-7f831871f8d1.png)
En Nombre de archivo solo dice Proyecto.
![image](https://user-images.githubusercontent.com/21196249/37595667-5eb777e6-2b58-11e8-8880-afd12a151813.png)

## Nuevas Observaciones en Sistema y Reporte
## Sistema
En la Ruta Gastos Personales/Geolocalización/Horarios

Campo Dias aparece sin tilde debe decir Días.
Dentro del mismo Campo Días muestra los días primero con (-) Guión y después muestra el día.
![image](https://user-images.githubusercontent.com/21196249/37614801-6bb0f616-2b8a-11e8-8b95-5d2ed80d6799.png)

Sistema - Listado de Gasto de Administración

Se sugiere que dentro del campo Beneficiario solo aparezca la cantidad. Así cuando sea solo un Beneficiario no dirá "Beneficiarios" en Plural.
![image](https://user-images.githubusercontent.com/21196249/37614879-9ba7baa8-2b8a-11e8-8fd6-c9fb94c66d7d.png)

En sección Competencias/Nombre Producto
Dentro de la grilla campo inicio aparece con minúscula al principio. Debe decir "Inicio"
Hora en campo Inicio y Fin deben estar ambas arriba o ambas abajo para que aparezca uniforme. 

![image](https://user-images.githubusercontent.com/21196249/37616529-0392b66e-2b8f-11e8-8858-85b7c768f00d.png)

## Formulario

Formulario Postulación de Proyectos Deportivos
Desde Página 1 a la 11
[Agregar Competencia_1-11.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/1826461/Agregar.Competencia_1-11.pdf)

Antecedentes del Postulante(Página 1)
En Campo Rut el Rut aparece sin dígito verificador.

En Ruta Gastos en Bienes y Servicios/ Dias(Página 5,6,7 y 8)
Campo Dias aparece sin tilde. Debe decir Días

[Agregar Competencia_12-19.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/1826487/Agregar.Competencia_12-19.pdf)

En sección Horarios de la Geolocalización campo Dias aparece sin tilde.(Página 13)
Dentro del campo día Miercoles aparece sin tilde.

En sección Gastos en Bienes y Servicios campo dice "Total Por beneficiario".  Debe decir "Total por Beneficiario". Con eso se mantiene uniformidad dentro de todos los campos de la grilla.(Página 17)

@felipedonoso @pabloespinoza 
Aquí finalicé las pruebas del reporte según lo solicitaste.
No obstante también nombre algunas mejoras para el sistema.
Si tienes alguna consulta me dices.

**Comment by felipedonoso** [comment]
Se revisa desde la visualización web el reporte:

**Producto 3:**

![image](https://user-images.githubusercontent.com/5757157/37598759-d6c741ae-2b61-11e8-8934-1c022930d6a1.png)

**Producto 4:**

![image](https://user-images.githubusercontent.com/5757157/37598800-f58f8722-2b61-11e8-9142-f52f24740ad4.png)

**Producto 5:**

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Se revisan los productos en Sistema

Producto 3:
En sistema "Competencia de XC en Puerto Montt"
![image](https://user-images.githubusercontent.com/21196249/37660377-0d10f532-2c31-11e8-9616-5043553ceb8c.png)

Producto 4:
En sistema "ORGANIZACIÓN DE COMPETENCIAS ANTOFAGASTA"
![image](https://user-images.githubusercontent.com/21196249/37660936-567f316a-2c32-11e8-95d8-0bc8b5a5783d.png)

Producto 5:
En sistema "Fútbol Calle"
![image](https://user-images.githubusercontent.com/21196249/37661089-ba548d84-2c32-11e8-9109-89a45a826a19.png)

Producto 6:
En sistema "Crossfit"
![image](https://user-images.githubusercontent.com/21196249/37661815-621b1c76-2c34-11e8-95fc-fcad25b12078.png)

**Comment by pabloespinoza** [comment]
Estimados, se corrigen las siguientes observaciones:
## Postulación
- Campo Dias aparece sin tilde debe decir Días.
- Dentro del mismo Campo Días muestra los días primero con (-) Guión y después muestra el día.
- Se sugiere que dentro del campo Beneficiario solo aparezca la cantidad. Así cuando sea solo un Beneficiario no dirá "Beneficiarios" en Plural. **(Se corrige para que, cuando sea un beneficiario se visualice Beneficiario y no Beneficiarios)**.
- Dentro de la grilla campo inicio aparece con minúscula al principio. Debe decir "Inicio"

## Reporte
- En Ruta Gastos en Bienes y Servicios/ Dias(Página 5,6,7 y 8)
Campo Dias aparece sin tilde. Debe decir Días
- En sección Horarios de la Geolocalización campo Dias aparece sin tilde.(Página 13)
Dentro del campo día Miercoles aparece sin tilde.
- En sección Gastos en Bienes y Servicios campo dice "Total Por beneficiario".  Debe decir "Total por Beneficiario". Con eso se mantiene uniformidad dentro de todos los campos de la grilla.(Página 17)
- Antecedentes del Postulante(Página 1)
En Campo Rut el Rut aparece sin dígito verificador. **(Esto ocurre por que en indReportesQA se utilizaba una url de RNO obsoleta (http://10.15.1.51/AltoRendimientoServices/Api/OrganizacionRNO), se actualiza a la nueva url (http://10.0.1.52/AltoRendimiento/WS/Api/OrganizacionRNO). Cabe destacar que en producción se visualiza correctamente)**

## No se logra reproducir el error: 
-ERROR:
![image.png](https://images.zenhubusercontent.com/5a674e6e4b5806bc2bc3f1ee/8c7ca26a-411e-475f-bd4d-d992fd959437 )

- Al presionar Exportar PDF sistema envío un mensaje de error por demora en la respuesta.

## Acuerdos pendientes:
- Hora en campo Inicio y Fin deben estar ambas arriba o ambas abajo para que aparezca uniforme. **(Esto depende de la dimensión de las otras columnas que hoy en día son automáticas, se debe acordar si dejar los campos de un ancho fijo para que esto no ocurra)**
- Se sugiere que dentro del campo Beneficiario solo aparezca la cantidad. Así cuando sea solo un Beneficiario no dirá "Beneficiarios" en Plural. **(Se debe acordar si mostrar o no el texto)**.

**Comment by felipedonoso** [comment]
Estimados:

@pabloespinoza como lo mencionaste ver como queda las 7 columnas en donde lo ideal sería inicio y fin del mismo tamaño.

Lo otro sobre los beneficiarios, que se conserve el título de Beneficiario(s) y que abajo aparezca el total de ellos y de no existir que aparezca el número 0.

**Comment by pabloespinoza** [comment]
Se corrige y se publica en QA.

**Comment by felipedonoso** [comment]
# CONCLUSIÓN:

**La tarea se encuentra terminada, ahora queda pendiente la revisión del lado de la Solicitud de cambio.**

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

## Se revisan las correcciones realizadas dentro del Sistema Postulación.

![image](https://user-images.githubusercontent.com/21196249/37732002-79903028-2d22-11e8-8b5d-91b0bd33f410.png)
Ahora campo Inicio aparece con mayúscula al principio.

![image](https://user-images.githubusercontent.com/21196249/37732010-7f309784-2d22-11e8-803f-3ace1ae37fb9.png)
Columna Días aparece con tilde y en campo Días ya no aparece (-) al principio de los días.

![image](https://user-images.githubusercontent.com/21196249/37732029-8b4c6f8e-2d22-11e8-8714-69cd23a59eba.png)
![image](https://user-images.githubusercontent.com/21196249/37732040-9186573e-2d22-11e8-9902-7105ded0c8c7.png)
En Editar Registro campo Descripción Objetivo ahora aparece con tilde.

![image](https://user-images.githubusercontent.com/21196249/37732440-c3259376-2d23-11e8-9fd2-2465cf9c92fb.png)
En campo Beneficiario solo aparece la cantidad. Así cuando sea solo un Beneficiario dice "Beneficiario(s)" mas la cantidad. En este caso 1.

![image](https://user-images.githubusercontent.com/21196249/37732606-483f8364-2d24-11e8-8f51-1b06ba507515.png)
Ahora dentro de la grilla campo Inicio aparece con mayúscula al principio.

Pablo muchas gracias por realizar los cambios.
Mañana reviso lo del Reporte.
