### ISSUE TITLE
<COMPETENCIAS><ELIMINAR RECINTO> ELIMINAR UN RECINTO QUE ESTE ASOCIADO A UNA COMPETENCIA

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#77]
Se eliminará un recinto desde la pestaña Recintos, y se visualizará el PDF del proyecto que contenga dicho recinto

**Comment by danteghirardelli** [comment]
## Se eliminará Recinto "Curauma" para Proyecto 1800042013 Nombre "Old Trafford" en estado "Aprobado / Solicitud de Cambio / En Construcción" Producto "Entrenamiento y Concentraciones"
![image](https://user-images.githubusercontent.com/21196249/38562420-e9e527c8-3cb0-11e8-943a-4b2775605454.png)
![image](https://user-images.githubusercontent.com/21196249/38562489-18cc564c-3cb1-11e8-8d68-59fdf67c303e.png)
![image](https://user-images.githubusercontent.com/21196249/38562547-3485b57c-3cb1-11e8-855d-84e58175d7d5.png)
## Lugar Curauma
![image](https://user-images.githubusercontent.com/21196249/38562601-57784284-3cb1-11e8-9a1d-0218fccb396c.png)
![image](https://user-images.githubusercontent.com/21196249/38562626-69175f8e-3cb1-11e8-8184-7da35031ec80.png)
![image](https://user-images.githubusercontent.com/21196249/38562659-798cb9b8-3cb1-11e8-9ecc-7ca764337755.png)
![image](https://user-images.githubusercontent.com/21196249/38562698-88b5a29c-3cb1-11e8-93e4-0c04de055d5a.png)
## Se revisa Reporte antes de los cambios.
![image](https://user-images.githubusercontent.com/21196249/38562813-ce2f526e-3cb1-11e8-9f86-480cdb517937.png)
![image](https://user-images.githubusercontent.com/21196249/38562892-0164495a-3cb2-11e8-895a-f64e2493b227.png)
## Exportar PDF
![image](https://user-images.githubusercontent.com/21196249/38563347-02a21abc-3cb3-11e8-99f5-560c44cc14dd.png)
![image](https://user-images.githubusercontent.com/21196249/38563496-65cc92fc-3cb3-11e8-8f6c-f553bdc0995d.png)
## PDF Antes de la eliminación del Recinto
[Proyecto - 1800042013_Antes de Eliminacion Recinto.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/1895061/Proyecto.-.1800042013_Antes.de.Eliminacion.Recinto.pdf)

## Desde Recintos se eliminan los recintos Curauma y prueba (fidel oteiza 1956)
![image](https://user-images.githubusercontent.com/21196249/38564094-c7dec608-3cb4-11e8-8d41-f132ae8f9da6.png)
![image](https://user-images.githubusercontent.com/21196249/38563940-6caca944-3cb4-11e8-81f4-547944010829.png)
![image](https://user-images.githubusercontent.com/21196249/38564179-fc4033e6-3cb4-11e8-8153-706e1c9b2235.png)
## Se elimina Recinto "prueba" Dirección fidel oteiza 1956
![image](https://user-images.githubusercontent.com/21196249/38564239-1e5400ac-3cb5-11e8-859a-f39a300d4730.png)
![image](https://user-images.githubusercontent.com/21196249/38564297-38b78f36-3cb5-11e8-9761-5308737a5096.png)
![image](https://user-images.githubusercontent.com/21196249/38564412-79cb8414-3cb5-11e8-8ca6-eb311dc5f457.png)
![image](https://user-images.githubusercontent.com/21196249/38564462-93309f66-3cb5-11e8-8cb0-bad3728fc177.png)
![image](https://user-images.githubusercontent.com/21196249/38564610-e05c5a82-3cb5-11e8-87b4-a6541218d106.png)
## Se intenta eliminar dos veces y aparecen repetidos
![image](https://user-images.githubusercontent.com/21196249/38565091-cbbc3420-3cb6-11e8-813b-7e0d83f61400.png)
## Se  consulta reporte Proyecto 1800042013 después de la eliminación de Recintos
![image](https://user-images.githubusercontent.com/21196249/38565790-969410ea-3cb8-11e8-82d0-a7b889b5395b.png)
![image](https://user-images.githubusercontent.com/21196249/38565824-abbf2806-3cb8-11e8-9442-f85b88e94449.png)
![image](https://user-images.githubusercontent.com/21196249/38565864-c380387c-3cb8-11e8-97f5-145589d8ba38.png)
## Exportar PDF después de la eliminación
[Proyecto - 1800042013_Despues de Eliminacion Recinto.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/1895182/Proyecto.-.1800042013_Despues.de.Eliminacion.Recinto.pdf)
## Se comparan los reportes y estos no sufren cambios.
![image](https://user-images.githubusercontent.com/21196249/38566688-a8780bf2-3cba-11e8-84d4-e57fb4ff1f12.png)
@felipedonoso @pabloespinoza 
Felipe tengo las impresiones físicas de los reportes.

**Comment by danteghirardelli** [comment]
## Se intenta eliminar Recinto "CAR" dirección "estadio nacional" 
![image](https://user-images.githubusercontent.com/21196249/38568209-7cd449d0-3cbe-11e8-8cf1-a05550fbca8f.png)
![image](https://user-images.githubusercontent.com/21196249/38568249-97c678f8-3cbe-11e8-9038-4fa5644dba2c.png)
![image](https://user-images.githubusercontent.com/21196249/38568266-a69d4f64-3cbe-11e8-8244-01105a2db45a.png)
Desaparece de la grilla.
![image](https://user-images.githubusercontent.com/21196249/38568312-b9bd9a22-3cbe-11e8-8b20-55b5840c7dc4.png)
Se presiona botón "Guardar"
![image](https://user-images.githubusercontent.com/21196249/38568365-d742ff56-3cbe-11e8-9c8b-0bfc5766b392.png)
![image](https://user-images.githubusercontent.com/21196249/38568480-200ac2a0-3cbf-11e8-8b34-074b0f8ab494.png)
![image](https://user-images.githubusercontent.com/21196249/38568546-4ec0d2f6-3cbf-11e8-91d6-287dbb65c9c7.png)
Si no se completan los campos requeridos no se puede eliminar.
Sabemos que si los completamos nuevamente en la grilla se agregará el nuevo recinto.
Es imposible eliminar el Recinto "CAR" dirección "estadio nacional" 
@felipedonoso @pabloespinoza

**Comment by felipedonoso** [comment]
# CONCLUSIÓN

**1. Se termina esta tarea debido a que no pudo concretarse con éxito.
2. Se creará una tarea enfocada a la pestaña Recintos.**

**Comment by danteghirardelli** [comment]
Crear proyecto "Capacitación New" para posteriormente crear una Solicitud de Cambio al producto Capacitación.
![image](https://user-images.githubusercontent.com/21196249/38681906-3ac89b12-3e40-11e8-822b-45b25e4d5adb.png)
![image](https://user-images.githubusercontent.com/21196249/38681918-42510ad6-3e40-11e8-90e1-067617763640.png)
![image](https://user-images.githubusercontent.com/21196249/38681935-4a81d28a-3e40-11e8-951e-958a6581c373.png)
![image](https://user-images.githubusercontent.com/21196249/38681951-51cb657e-3e40-11e8-9f0a-0e28b1e21ca5.png)
![image](https://user-images.githubusercontent.com/21196249/38681963-58045fa4-3e40-11e8-9286-68df3d09a27d.png)
![image](https://user-images.githubusercontent.com/21196249/38681974-5f4345b4-3e40-11e8-940a-b6e99ee3e389.png)
![image](https://user-images.githubusercontent.com/21196249/38681984-65d79f4c-3e40-11e8-802f-0e1bfbf6b19e.png)
![image](https://user-images.githubusercontent.com/21196249/38681997-6d7d4a94-3e40-11e8-95ed-1d0c6aa095c6.png)
![image](https://user-images.githubusercontent.com/21196249/38682006-729cf128-3e40-11e8-8e77-1a8a03836a7d.png)
![image](https://user-images.githubusercontent.com/21196249/38682021-79d01dc6-3e40-11e8-9279-0cf2d030512f.png)
![image](https://user-images.githubusercontent.com/21196249/38682032-7f5f2ffc-3e40-11e8-9e3a-3e9165a78e24.png)
![image](https://user-images.githubusercontent.com/21196249/38682039-866dc81c-3e40-11e8-9c61-fe011bc7806e.png)
![image](https://user-images.githubusercontent.com/21196249/38682061-8cdbb1f0-3e40-11e8-8987-b451af6dd99d.png)
![image](https://user-images.githubusercontent.com/21196249/38682069-91fd139a-3e40-11e8-9fe8-5f8518493354.png)
![image](https://user-images.githubusercontent.com/21196249/38682076-9600070e-3e40-11e8-8061-89f07c2b4e9a.png)
![image](https://user-images.githubusercontent.com/21196249/38682088-9b39e15e-3e40-11e8-8d28-2723a1e0e11c.png)
![image](https://user-images.githubusercontent.com/21196249/38682095-a080d604-3e40-11e8-9ccd-136269b5552c.png)
![image](https://user-images.githubusercontent.com/21196249/38682108-a5522034-3e40-11e8-8a44-4107b6487251.png)
![image](https://user-images.githubusercontent.com/21196249/38682113-a9aa72c6-3e40-11e8-9b13-cc33733758b5.png)
![image](https://user-images.githubusercontent.com/21196249/38682119-aea1c950-3e40-11e8-822b-711d0002f0e9.png)
![image](https://user-images.githubusercontent.com/21196249/38682127-b382267c-3e40-11e8-80bd-63a9750d0677.png)
![image](https://user-images.githubusercontent.com/21196249/38682136-b79f1b02-3e40-11e8-9a37-c219ca127075.png)
![image](https://user-images.githubusercontent.com/21196249/38682150-bf0ea88a-3e40-11e8-8afa-6bb5f45216cb.png)
![image](https://user-images.githubusercontent.com/21196249/38682161-c90caea4-3e40-11e8-8349-02fff255a89a.png)
![image](https://user-images.githubusercontent.com/21196249/38682165-cdce689c-3e40-11e8-9830-5340cad85f89.png)
![image](https://user-images.githubusercontent.com/21196249/38682172-d33f877a-3e40-11e8-8d22-2037879750bb.png)
![image](https://user-images.githubusercontent.com/21196249/38682180-d8803932-3e40-11e8-9ab1-dbb675d8904d.png)
![image](https://user-images.githubusercontent.com/21196249/38682194-de6e845c-3e40-11e8-833d-6e3e2b4e3dcd.png)
![image](https://user-images.githubusercontent.com/21196249/38682202-e3ab3cee-3e40-11e8-88ea-e87fcbf71a02.png)
![image](https://user-images.githubusercontent.com/21196249/38682212-e898d9aa-3e40-11e8-8281-c0555a8f1400.png)
![image](https://user-images.githubusercontent.com/21196249/38682219-edb02132-3e40-11e8-81b0-4ec8f7e5c3e4.png)
![image](https://user-images.githubusercontent.com/21196249/38682229-f2db3bd8-3e40-11e8-98c8-9735bc59d418.png)
![image](https://user-images.githubusercontent.com/21196249/38682243-f86b2cc0-3e40-11e8-85fc-5325256ce0d4.png)
@felipedonoso @pabloespinoza 
Se continúa con creación de proyecto "Capacitación New"

**Comment by danteghirardelli** [comment]
## Se avanza con proyecto "Capacitación New"
Horarios
![image](https://user-images.githubusercontent.com/21196249/38685703-e3c376d0-3e48-11e8-8b50-ee50c9c8b6b3.png)
![image](https://user-images.githubusercontent.com/21196249/38685804-2527e674-3e49-11e8-979a-b764df48c21b.png)
![image](https://user-images.githubusercontent.com/21196249/38685957-9555e3d8-3e49-11e8-8a69-a5ae34b88f46.png)
![image](https://user-images.githubusercontent.com/21196249/38686116-f67c0520-3e49-11e8-9aa2-adcdb0ff1653.png)
![image](https://user-images.githubusercontent.com/21196249/38687238-8ea3ca5c-3e4c-11e8-94ae-58d6b6f72b5e.png)
![image](https://user-images.githubusercontent.com/21196249/38687292-b70759a0-3e4c-11e8-801b-1551907ec877.png)
## Verificar
![image](https://user-images.githubusercontent.com/21196249/38687644-868f5f42-3e4d-11e8-8fc1-7f845a1ae2f7.png)
![image](https://user-images.githubusercontent.com/21196249/38687705-abe042de-3e4d-11e8-8b27-2bea06ee45d7.png)
![image](https://user-images.githubusercontent.com/21196249/38687744-be673e12-3e4d-11e8-87a4-d3d46712f7f3.png)
## Evaluar Proyecto Ingresado
![image](https://user-images.githubusercontent.com/21196249/38688092-9ee17aac-3e4e-11e8-8ff3-b25b28407b71.png)
![image](https://user-images.githubusercontent.com/21196249/38688138-b9564e6c-3e4e-11e8-9827-182a1daa451c.png)
![image](https://user-images.githubusercontent.com/21196249/38688162-cd0d4140-3e4e-11e8-8b5b-93a40fc2c134.png)
![image](https://user-images.githubusercontent.com/21196249/38688196-e5abdd60-3e4e-11e8-864f-ded689015012.png)
![image](https://user-images.githubusercontent.com/21196249/38688228-fbd7c202-3e4e-11e8-9c53-e21f141c8106.png)
![image](https://user-images.githubusercontent.com/21196249/38688277-0c5fe94c-3e4f-11e8-94b8-2536039edc81.png)
## Verificar y Postular
![image](https://user-images.githubusercontent.com/21196249/38689449-1cbe5294-3e52-11e8-9f3a-d9fe842c6101.png)
![image](https://user-images.githubusercontent.com/21196249/38689622-7eae60f2-3e52-11e8-8940-64e96f08c6ab.png)
![image](https://user-images.githubusercontent.com/21196249/38689664-93ec6be4-3e52-11e8-9020-0683021669a8.png)
## Evaluar Proyecto
![image](https://user-images.githubusercontent.com/21196249/38689955-4d2fd820-3e53-11e8-8abd-f13f74084774.png)
![image](https://user-images.githubusercontent.com/21196249/38690104-aacea128-3e53-11e8-85af-7b30c0da3fcc.png)
![image](https://user-images.githubusercontent.com/21196249/38690188-e833d006-3e53-11e8-8c74-6aa3b1afdb13.png)
## Pre seleccionar Proyecto
![image](https://user-images.githubusercontent.com/21196249/38699026-487d3e20-3e6d-11e8-9f3e-ca22211452cb.png)
![image](https://user-images.githubusercontent.com/21196249/38699061-62dc5fbc-3e6d-11e8-8ba5-17e6135d0468.png)
![image](https://user-images.githubusercontent.com/21196249/38699179-b6d0315c-3e6d-11e8-8234-edfbcf5bcb90.png)

## Evaluar Proyecto 1800042016 Pre Seleccionado
![image](https://user-images.githubusercontent.com/21196249/38699306-0ca3f834-3e6e-11e8-8a6e-21df0d3ba14e.png)
![image](https://user-images.githubusercontent.com/21196249/38699445-6f044768-3e6e-11e8-81b1-cf69f08976c3.png)
![image](https://user-images.githubusercontent.com/21196249/38699477-86d82cba-3e6e-11e8-9f67-7e20e5a44c45.png)
![image](https://user-images.githubusercontent.com/21196249/38699520-9d021f8c-3e6e-11e8-812b-c28c0b4f1ca5.png)
![image](https://user-images.githubusercontent.com/21196249/38699548-b0aef906-3e6e-11e8-9ab9-d1b6da763bcf.png)
![image](https://user-images.githubusercontent.com/21196249/38699602-dac06360-3e6e-11e8-9333-d2e117fb30ff.png)
![image](https://user-images.githubusercontent.com/21196249/38699670-0bb0d176-3e6f-11e8-8279-157aae50dc3e.png)
![image](https://user-images.githubusercontent.com/21196249/38699700-239f781e-3e6f-11e8-9662-74e8c5f69b98.png)
![image](https://user-images.githubusercontent.com/21196249/38699741-41b2c19e-3e6f-11e8-8eb3-2e3d3159d74f.png)
![image](https://user-images.githubusercontent.com/21196249/38699761-5312293e-3e6f-11e8-813a-f650560ccefa.png)
![image](https://user-images.githubusercontent.com/21196249/38699798-75726818-3e6f-11e8-937f-5e5380f9884f.png)
Se aprueba proyecto 1800042016
![image](https://user-images.githubusercontent.com/21196249/38699835-982c4c52-3e6f-11e8-94b8-3b4cc5e3da5b.png)
@felipedonoso @pabloespinoza 
Mañana se continúa con la SC para el producto Capacitación

**Comment by danteghirardelli** [comment]
## Realizar SC a Proyecto N° 1800042016 
![image](https://user-images.githubusercontent.com/21196249/38739846-7034c39e-3f0c-11e8-8c24-7c3f716dff22.png)
![image](https://user-images.githubusercontent.com/21196249/38741926-882c025a-3f11-11e8-8433-54eb466b803b.png)
![image](https://user-images.githubusercontent.com/21196249/38742004-b6a6a1da-3f11-11e8-944b-f34362dc2a78.png)
![image](https://user-images.githubusercontent.com/21196249/38742028-cbff708e-3f11-11e8-9e7e-f40b5c236be4.png)

**Comment by danteghirardelli** [comment]
## Crear nuevo Proyecto para posteriormente realizar la SC
![image](https://user-images.githubusercontent.com/21196249/38810887-76fc54a4-415e-11e8-8bfd-c60282b3f6ed.png)
![image](https://user-images.githubusercontent.com/21196249/38811088-104ded7a-415f-11e8-975c-2603ed96ee89.png)
![image](https://user-images.githubusercontent.com/21196249/38811122-2b52732a-415f-11e8-8268-2f9e03a32ba6.png)
![image](https://user-images.githubusercontent.com/21196249/38811308-946c4c64-415f-11e8-8843-5a887cb17580.png)

**Comment by danteghirardelli** [comment]
## Se creará SC para proyecto N° 1800042017
![image](https://user-images.githubusercontent.com/21196249/38869538-693c1e30-4221-11e8-9f67-63f7f04df937.png)
Generar SC
![image](https://user-images.githubusercontent.com/21196249/38869715-000742ae-4222-11e8-8772-c81b703b35b6.png)

**Comment by danteghirardelli** [comment]
SC para proyecto 1800042017 "Entrenamiento y Concentraciones Reload" enviada correctamente
@felipedonoso @pabloespinoza

**Comment by danteghirardelli** [comment]
## Crear nuevo proyecto "Organización de Competencias Reload 2"
![image](https://user-images.githubusercontent.com/21196249/38932739-74f873dc-42ed-11e8-9892-083691251ec9.png)
![image](https://user-images.githubusercontent.com/21196249/38933013-3004f27c-42ee-11e8-986b-3a79218b7009.png)
![image](https://user-images.githubusercontent.com/21196249/38934656-abdcc93e-42f2-11e8-96aa-0c42f0de5b01.png)
## Agregar Producto
![image](https://user-images.githubusercontent.com/21196249/38936292-dead4ed4-42f6-11e8-8380-4a8b1b737198.png)
