### ISSUE TITLE
<MONTO PROYECTO>en la bandeja de proyectos POSTULACIÓN

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#87]
REVISAR la sumatoría de gastos de los productos asociados al proyecto, verificar los estados que está leyendo.

Este es el código con problemas:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/9f9a8923-fc11-491c-9531-8a8f20a8837e)

Saludos,

**Comment by pabloespinoza** [comment]
Actualmente el proyecto está con solicitud de cambio en construcción, el monto original del proyecto es de $37.683.300 y en la solicitud de cambio hasta el momento se han utilizado $34.433.310, falta que se completen $3.249.990. Dado que no se ha utilizado todo el monto del proyecto, arroja el error cuando se intenta enviar la solicitud de cambio a revisión, quedando en evidencia en la imagen siguiente:

![image.png](https://images.zenhubusercontent.com/5a674e6e4b5806bc2bc3f1ee/97409e17-0981-496f-8fe0-c20cd4f5417a)

**Comment by felipedonoso** [comment]
@danteghirardelli estimado; 

Necesito que realice lo siguiente:

Crear un proyecto y llevarlo hasta la aprobación. Adjuntar el reporte.
Crear una SC, elimine un gasto.
Descargue el reporte desde postulación.

El monto del proyecto siempre debería ser el mismo,

**Comment by danteghirardelli** [comment]
### Se creará nuevo Proyecto entidad ADO para posteriormente realizar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/42966430-1fcd73aa-8b6b-11e8-95fb-f1e39f19a035.png)
![image](https://user-images.githubusercontent.com/21196249/42966445-2a074846-8b6b-11e8-8e71-b95d76a2b67a.png)
![image](https://user-images.githubusercontent.com/21196249/42966456-32764644-8b6b-11e8-8d20-59dd257bc4e7.png)
![image](https://user-images.githubusercontent.com/21196249/42966464-38d3f612-8b6b-11e8-8321-3fa7e3b03a09.png)
![image](https://user-images.githubusercontent.com/21196249/42966474-40b31caa-8b6b-11e8-8ef6-5af1c8d33640.png)
![image](https://user-images.githubusercontent.com/21196249/42966487-474077ca-8b6b-11e8-947d-7c1111d0759a.png)
![image](https://user-images.githubusercontent.com/21196249/42966493-4e60e562-8b6b-11e8-99c9-1e1103e42029.png)
![image](https://user-images.githubusercontent.com/21196249/42966499-544b2438-8b6b-11e8-8872-8177c01e134e.png)
![image](https://user-images.githubusercontent.com/21196249/42966506-5a9fdd74-8b6b-11e8-9ed9-da6714dc01d7.png)
![image](https://user-images.githubusercontent.com/21196249/42966511-60b9aafa-8b6b-11e8-9dd1-49450a5b59c6.png)
![image](https://user-images.githubusercontent.com/21196249/42966513-66d5338c-8b6b-11e8-8505-d09e732f20db.png)
![image](https://user-images.githubusercontent.com/21196249/42966524-6ef9426a-8b6b-11e8-9fdd-0f654d5a3c3b.png)
![image](https://user-images.githubusercontent.com/21196249/42966534-7643c658-8b6b-11e8-9b25-ea0fead197a4.png)
![image](https://user-images.githubusercontent.com/21196249/42966537-7c7899a4-8b6b-11e8-8bcc-c6dafd7e7c82.png)
![image](https://user-images.githubusercontent.com/21196249/42966552-8a58eb5a-8b6b-11e8-8245-39ca58e1055f.png)
![image](https://user-images.githubusercontent.com/21196249/42966945-ab3ca2ca-8b6c-11e8-8b60-ff7842091a49.png)
![image](https://user-images.githubusercontent.com/21196249/42967181-75ab9f0c-8b6d-11e8-8af3-6eff33bd1f1a.png)
![image](https://user-images.githubusercontent.com/21196249/42967208-89351c6a-8b6d-11e8-91d2-1fe4449d183d.png)
![image](https://user-images.githubusercontent.com/21196249/42967234-9c918d7a-8b6d-11e8-8cb7-12eebdea3fd6.png)
![image](https://user-images.githubusercontent.com/21196249/42967448-47a89866-8b6e-11e8-9514-e74bce38c0f3.png)
![image](https://user-images.githubusercontent.com/21196249/42967473-58ca3f5a-8b6e-11e8-8b93-0c517aaf2b88.png)
![image](https://user-images.githubusercontent.com/21196249/42967525-83cbb62a-8b6e-11e8-9486-8df4589b379a.png)
### Gastos en Bienes y Raíces
![image](https://user-images.githubusercontent.com/21196249/42967576-ace775ee-8b6e-11e8-84b0-e5282eb3113c.png)
![image](https://user-images.githubusercontent.com/21196249/42967596-c15e6140-8b6e-11e8-835a-1893c3d8b0f6.png)
@felipedonoso @pabloespinoza 
Se continúa con la creación de Proyecto.

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
### Se realizará Solicitud Cambio Proyecto 1800042030
![image](https://user-images.githubusercontent.com/21196249/43013203-29f799b8-8c16-11e8-8e73-b62b24b036e1.png)
### Generar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/43013428-e443d8d6-8c16-11e8-935d-aba6320ce03a.png)
![image](https://user-images.githubusercontent.com/21196249/43013528-2fed150e-8c17-11e8-8e1f-ecc3bc0e70a4.png)
![image](https://user-images.githubusercontent.com/21196249/43013553-42e5a888-8c17-11e8-9f03-3647841a1a1a.png)
### Se modifican los Gastos
![image](https://user-images.githubusercontent.com/21196249/43013761-f1a03bfe-8c17-11e8-9ff1-8ba2aee8c1c7.png)
### En Reporte se mantiene correctamente el Monto $11.000.000 original
![image](https://user-images.githubusercontent.com/21196249/43014197-671c5420-8c19-11e8-9bbb-77182cc3ff29.png)
![image](https://user-images.githubusercontent.com/21196249/43014347-e621a00e-8c19-11e8-862a-0ceb5ecca7b3.png)
Se modificó el Gasto sin aprobar la Solicitud de Cambio. Reporte se mantiene con monto Real y original.
Prueba solicitada se da por aprobada.
@felipedonoso @pabloespinoza 
Gracias Pablo por la ayuda.

**Comment by danteghirardelli** [comment]
### Se crea nuevo Proyecto COCH
![image](https://user-images.githubusercontent.com/21196249/43087365-bbd32218-8e6d-11e8-997d-63b5afb41425.png)
![image](https://user-images.githubusercontent.com/21196249/43087378-c2c80f52-8e6d-11e8-905f-5378247b471d.png)
![image](https://user-images.githubusercontent.com/21196249/43087400-ce5dc3c0-8e6d-11e8-8952-ed7dbd2d5899.png)
![image](https://user-images.githubusercontent.com/21196249/43087433-dedddf00-8e6d-11e8-8655-a7a3e42dc807.png)
![image](https://user-images.githubusercontent.com/21196249/43087445-e671ba2a-8e6d-11e8-9039-493c46ea12ca.png)
![image](https://user-images.githubusercontent.com/21196249/43087455-ed271ae0-8e6d-11e8-8aa5-c91a6608fbdd.png)
![image](https://user-images.githubusercontent.com/21196249/43087465-f36e5e68-8e6d-11e8-9b4d-b4c01bbfe0fc.png)
![image](https://user-images.githubusercontent.com/21196249/43087475-f80adbc2-8e6d-11e8-9f59-5f3af69927ee.png)
![image](https://user-images.githubusercontent.com/21196249/43087484-fea091e8-8e6d-11e8-8a07-2da76f1af34b.png)
![image](https://user-images.githubusercontent.com/21196249/43087503-08e71550-8e6e-11e8-8fed-185a62cf0b49.png)
![image](https://user-images.githubusercontent.com/21196249/43087512-0f6c92a6-8e6e-11e8-9ad0-2b144b11b135.png)
![image](https://user-images.githubusercontent.com/21196249/43087522-1533fd8c-8e6e-11e8-87c1-5d82af93d564.png)
![image](https://user-images.githubusercontent.com/21196249/43087542-1d70e370-8e6e-11e8-904d-fa9bf000085a.png)
![image](https://user-images.githubusercontent.com/21196249/43087555-23574324-8e6e-11e8-8fbf-9245fa50b467.png)
![image](https://user-images.githubusercontent.com/21196249/43087569-2b955efe-8e6e-11e8-8bfa-36dd8c8494d6.png)
![image](https://user-images.githubusercontent.com/21196249/43087577-3226d004-8e6e-11e8-951f-c78c9e3789cf.png)
![image](https://user-images.githubusercontent.com/21196249/43087602-3b91fd9e-8e6e-11e8-8b8e-8e32eb5bab3e.png)
![image](https://user-images.githubusercontent.com/21196249/43087617-4a7eaa3c-8e6e-11e8-9435-fde14f5f2587.png)
![image](https://user-images.githubusercontent.com/21196249/43087800-b311cd2c-8e6e-11e8-9755-fe96a1af21e3.png)
![image](https://user-images.githubusercontent.com/21196249/43087809-b753edc0-8e6e-11e8-9b12-09e1afca77d0.png)
![image](https://user-images.githubusercontent.com/21196249/43087811-bbef4352-8e6e-11e8-87f3-6e4cfa008c7d.png)
![image](https://user-images.githubusercontent.com/21196249/43087821-c22a1d64-8e6e-11e8-862d-d6963fa77003.png)
![image](https://user-images.githubusercontent.com/21196249/43087829-ca2a8bb6-8e6e-11e8-940f-d40c008bd0cc.png)
![image](https://user-images.githubusercontent.com/21196249/43087841-d1266d86-8e6e-11e8-87c8-c31896f67959.png)
![image](https://user-images.githubusercontent.com/21196249/43087850-d6c19e5a-8e6e-11e8-9c4e-0660f14ad152.png)
![image](https://user-images.githubusercontent.com/21196249/43087859-dbf43eaa-8e6e-11e8-81ab-80c9efe6675f.png)
![image](https://user-images.githubusercontent.com/21196249/43087865-e0aa7eb4-8e6e-11e8-8e39-53cf3ca2f348.png)
![image](https://user-images.githubusercontent.com/21196249/43087874-e5ba029e-8e6e-11e8-99da-af0ad1524915.png)
![image](https://user-images.githubusercontent.com/21196249/43087884-e97e0920-8e6e-11e8-9dbf-e009e0a1041d.png)
![image](https://user-images.githubusercontent.com/21196249/43087898-ed7e0368-8e6e-11e8-8f1f-e42c618dc0db.png)
![image](https://user-images.githubusercontent.com/21196249/43087908-f1dcb936-8e6e-11e8-8f52-a1a9ba86946d.png)
![image](https://user-images.githubusercontent.com/21196249/43087916-f678c96c-8e6e-11e8-932e-136e45b8d96a.png)
![image](https://user-images.githubusercontent.com/21196249/43087932-fb0e3386-8e6e-11e8-9e83-a4e9e5721c1c.png)
![image](https://user-images.githubusercontent.com/21196249/43087938-ffd2f9e2-8e6e-11e8-94d4-12840678375b.png)
![image](https://user-images.githubusercontent.com/21196249/43088091-576d2c2c-8e6f-11e8-84e9-c81a95682c68.png)
![image](https://user-images.githubusercontent.com/21196249/43088109-646842cc-8e6f-11e8-94e9-950b87fed402.png)
### Proyecto 1800042031 Postulado
![image](https://user-images.githubusercontent.com/21196249/43088620-95b61664-8e70-11e8-8f84-24a40e05d1f3.png)
@felipedonoso @pabloespinoza

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Continuar con Proyecto 1800042031
Evaluar Proyecto
![image](https://user-images.githubusercontent.com/21196249/43088996-937b1f06-8e71-11e8-834e-760e56425bba.png)
![image](https://user-images.githubusercontent.com/21196249/43089053-b5707c1e-8e71-11e8-8a9b-76ad39964c7e.png)
![image](https://user-images.githubusercontent.com/21196249/43089091-cfaf6568-8e71-11e8-9090-9bfda463125e.png)
![image](https://user-images.githubusercontent.com/21196249/43089139-f3ab2600-8e71-11e8-872a-9e0142025706.png)
![image](https://user-images.githubusercontent.com/21196249/43089810-a209063a-8e73-11e8-9a50-d1db203bdb2a.png)
![image](https://user-images.githubusercontent.com/21196249/43089833-b31958b2-8e73-11e8-8bfc-8aae95d0e7ad.png)
### Proyecto Seleccionado
![image](https://user-images.githubusercontent.com/21196249/43089917-eecee836-8e73-11e8-8873-72909e14b321.png)
![image](https://user-images.githubusercontent.com/21196249/43089980-20c9b8f2-8e74-11e8-8610-c1d352efb9d4.png)
![image](https://user-images.githubusercontent.com/21196249/43090025-3c5a2d54-8e74-11e8-8d95-b87894c52a89.png)
![image](https://user-images.githubusercontent.com/21196249/43090071-5fc2986c-8e74-11e8-9e4b-6edb739c68f2.png)
![image](https://user-images.githubusercontent.com/21196249/43090281-f34abeac-8e74-11e8-8b67-fa3b3c78d1d2.png)
![image](https://user-images.githubusercontent.com/21196249/43090383-31ca4b0c-8e75-11e8-9b38-f620661b16bf.png)

**Comment by danteghirardelli** [comment]
### Se creará Solicitud de Cambio para Proyecto 1800042031
![image](https://user-images.githubusercontent.com/21196249/43091150-5cd37e0c-8e77-11e8-8961-10c89be46b22.png)
### Generar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/43091563-64d20848-8e78-11e8-971c-9102c36c1e03.png)
![image](https://user-images.githubusercontent.com/21196249/43092074-f3d8b8e2-8e79-11e8-9831-8aad8869f965.png)
![image](https://user-images.githubusercontent.com/21196249/43092093-0622e02c-8e7a-11e8-943e-f69de3c7a8c8.png)
![image](https://user-images.githubusercontent.com/21196249/43092140-2a557270-8e7a-11e8-8757-1d592fc67f75.png)
![image](https://user-images.githubusercontent.com/21196249/43092182-528c2536-8e7a-11e8-9561-ec1fabc28efa.png)
![image](https://user-images.githubusercontent.com/21196249/43092228-77098944-8e7a-11e8-896d-4d64047f13e6.png)
![image](https://user-images.githubusercontent.com/21196249/43092249-8b86c33c-8e7a-11e8-8eb5-61f19722e49d.png)
![image](https://user-images.githubusercontent.com/21196249/43092270-9c0513da-8e7a-11e8-83ef-b11ebfc1fa63.png)
### Enviar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/43092468-505fadf4-8e7b-11e8-8bce-bec78d3ffcf1.png)
![image](https://user-images.githubusercontent.com/21196249/43092497-6284967a-8e7b-11e8-96f8-0091ae7de13e.png)
![image](https://user-images.githubusercontent.com/21196249/43092629-c787f9f4-8e7b-11e8-8f9d-dbcbfcf1eef6.png)
![image](https://user-images.githubusercontent.com/21196249/43092693-fb84c41c-8e7b-11e8-8381-e24cc6affe6f.png)
Consultar por mensaje
Se ingresa Gasto en Bienes y Servicios que supera El Monto Total del Proyecto originalmente Aprobado $10 millones.
![image](https://user-images.githubusercontent.com/21196249/43093981-afe049a6-8e7f-11e8-8dfe-4d4901a7f572.png)
Se modifica Total del Proyecto por uno válido.
![image](https://user-images.githubusercontent.com/21196249/43094130-1b61349c-8e80-11e8-9673-a67009e49ec3.png)
@felipedonoso @pabloespinoza 
Se continúa con la Solicitud de Cambio.

**Comment by danteghirardelli** [comment]
Postulación: 
http://10.15.1.51/AltoRendimientoQA
Usuario: 15314968
Contraseña: federacion

### Se sigue con la Solicitud de Cambio para proyecto 1800042031
![image](https://user-images.githubusercontent.com/21196249/43144524-55f738c6-8f2b-11e8-81ee-7b54540aac07.png)
![image](https://user-images.githubusercontent.com/21196249/43146202-bfc1da42-8f2e-11e8-983f-ffa1edcbfbbd.png)
![image](https://user-images.githubusercontent.com/21196249/43146328-0510f308-8f2f-11e8-8c56-afa5d5617841.png)
![image](https://user-images.githubusercontent.com/21196249/43146382-1eb3b250-8f2f-11e8-9bd8-e117e8816920.png)
![image](https://user-images.githubusercontent.com/21196249/43146517-5f3c189e-8f2f-11e8-9c8e-ce7aa1942334.png)
### Eliminar Solicitud de Cambio
![image](https://user-images.githubusercontent.com/21196249/43147099-361bcbc0-8f30-11e8-90ce-db5b3e01caf9.png)
![image](https://user-images.githubusercontent.com/21196249/43147231-8d50c4d6-8f30-11e8-883f-09b3cf166053.png)
![image](https://user-images.githubusercontent.com/21196249/43147337-cfb712da-8f30-11e8-83be-1b4ae9ab2396.png)
![image](https://user-images.githubusercontent.com/21196249/43147572-587d33ce-8f31-11e8-9274-6c0594fbaae4.png)
![image](https://user-images.githubusercontent.com/21196249/43147980-54850390-8f32-11e8-8c1a-5dcf069c7eef.png)
@felipedonoso @pabloespinoza 
¿Por qué cambio el Monto?

**Comment by danteghirardelli** [comment]
**Costo total del producto: 10.000.000**

1. Agregar un gasto en bienes y servicios por $6.000.000, buscando como fin validar la regla del 5%.
2. El sistema valido dicha prueba, indicando que el monto del **producto supera los 10.000.000.**
3. Se modifica el gasto por 5.000.000, se vuelve a validar y **aparece el mensaje de la regla del 5%**.
4. Se Elimina la SC, y el sistema tiene un error al indicar el monto del producto que paso de 10.000.000 a 15.000.000.
@felipedonoso @pabloespinoza

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
### Crear nuevo Proyecto COCH "Tubito"
![image](https://user-images.githubusercontent.com/21196249/43152817-8db7234a-8f3d-11e8-8f46-3611f2cc6c10.png)

@felipedonoso @pabloespinoza 
Revisemos Proyecto 1800042032

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Se realiza Solicitud de Cambio para Proyecto 1800042033

**Comment by danteghirardelli** [comment]
### Crear nuevo Proyecto COCH y posteriormente aprobar una Solicitud cambio.
![image](https://user-images.githubusercontent.com/21196249/43207343-d740b5c2-8ff5-11e8-8efb-f48e4dc0f70d.png)
![image](https://user-images.githubusercontent.com/21196249/43207655-8b42c22c-8ff6-11e8-81ed-cfe84ba0483b.png)
![image](https://user-images.githubusercontent.com/21196249/43207754-bdc40cf6-8ff6-11e8-93af-e24f3be6a097.png)
![image](https://user-images.githubusercontent.com/21196249/43207894-16e3125a-8ff7-11e8-9d8d-7e1839d66da1.png)
![image](https://user-images.githubusercontent.com/21196249/43208287-1718a2b6-8ff8-11e8-8791-05e351d58362.png)
![image](https://user-images.githubusercontent.com/21196249/43208814-3ad7659c-8ff9-11e8-9699-0db9ce0694d6.png)
![image](https://user-images.githubusercontent.com/21196249/43209055-be162c9a-8ff9-11e8-92a5-6fe42bf8b904.png)
![image](https://user-images.githubusercontent.com/21196249/43209152-f7750a88-8ff9-11e8-8816-aef8180fb672.png)
@felipedonoso @pabloespinoza 
Se continua con la creación de Proyecto "Usted Sabe"

**Comment by danteghirardelli** [comment]
Proyecto "Usted Sabe"
![image](https://user-images.githubusercontent.com/21196249/43211145-d7ce00cc-8ffe-11e8-904a-271ec2a4e9c6.png)
![image](https://user-images.githubusercontent.com/21196249/43211284-2f33cb12-8fff-11e8-8408-c8c263f4f09a.png)
![image](https://user-images.githubusercontent.com/21196249/43211327-44707ac0-8fff-11e8-81b8-26fd6196ff6f.png)
![image](https://user-images.githubusercontent.com/21196249/43211466-8cbfbdc2-8fff-11e8-9c1a-c06f1f24e6eb.png)
![image](https://user-images.githubusercontent.com/21196249/43211957-caf38e60-9000-11e8-9f1e-97e4706d8dd2.png)
![image](https://user-images.githubusercontent.com/21196249/43211990-e06eb396-9000-11e8-867c-a62b385ba446.png)
![image](https://user-images.githubusercontent.com/21196249/43212034-f8f80822-9000-11e8-91c1-f980acbfda8f.png)
![image](https://user-images.githubusercontent.com/21196249/43212083-18ad7058-9001-11e8-8156-f6db60cef50c.png)
![image](https://user-images.githubusercontent.com/21196249/43212168-4235b19c-9001-11e8-9b75-0beb9d22bd9b.png)
![image](https://user-images.githubusercontent.com/21196249/43212227-695fc302-9001-11e8-947e-59a396f876d3.png)
![image](https://user-images.githubusercontent.com/21196249/43212949-559a150a-9003-11e8-857c-0fc480fb0478.png)
![image](https://user-images.githubusercontent.com/21196249/43213016-7e325f9a-9003-11e8-9b7c-4fda88592b60.png)
![image](https://user-images.githubusercontent.com/21196249/43213132-c9685c12-9003-11e8-8397-c3d41660da22.png)
![image](https://user-images.githubusercontent.com/21196249/43225522-4d46e47c-9027-11e8-991d-7ed221c24221.png)
### Geolocalización
![image](https://user-images.githubusercontent.com/21196249/43225778-ff156804-9027-11e8-85a4-9ba799837645.png)
![image](https://user-images.githubusercontent.com/21196249/43225817-108dae5c-9028-11e8-91e8-a8f7c5973c18.png)
![image](https://user-images.githubusercontent.com/21196249/43225843-23514bac-9028-11e8-8046-843fe3268e5a.png)
@felipedonoso @pabloespinoza 
Se continua con el proyecto.

**Comment by felipedonoso** [comment]
### Retomando el error detectado por @danteghirardelli 👍 

```
Costo total del producto: 10.000.000

Agregar un gasto en bienes y servicios por $6.000.000, buscando como fin validar la regla del 5%.
El sistema valido dicha prueba, indicando que el monto del producto supera los 10.000.000.
Se modifica el gasto por 5.000.000, se vuelve a validar y aparece el mensaje de la regla del 5%.
Se Elimina la SC, y el sistema tiene un error al indicar el monto del producto que paso de 10.000.000 a 15.000.000.
```

1.- Se bajará le gasto en personal para poder obtener los 6.000.000 para bienes y servicios.

De 10.000.000 a 6.000.000:

![image](https://user-images.githubusercontent.com/5757157/43227473-d1cd8b6a-902c-11e8-9ea0-6afe931fbd84.png)

![image](https://user-images.githubusercontent.com/5757157/43227546-ff910c48-902c-11e8-8bf0-eea8279170db.png)

2.- Modificando el monto a 5 millones:

![image](https://user-images.githubusercontent.com/5757157/43227596-24fdd90c-902d-11e8-8b06-5812de3a8d70.png)

![image](https://user-images.githubusercontent.com/5757157/43227629-3d6276b0-902d-11e8-8317-95df26d2459e.png)

3.- Se elimina la SC:

![image](https://user-images.githubusercontent.com/5757157/43227654-5341d1b0-902d-11e8-8b40-91c150ca517a.png)

El error a sido corregido se elimina la SC y el proyecto vuelve al monto original:

![image](https://user-images.githubusercontent.com/5757157/43227692-747671b0-902d-11e8-8c68-c32f02f4e3f5.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
### Verificar Proyecto
![image](https://user-images.githubusercontent.com/21196249/43226237-44b96418-9029-11e8-8953-2c38cb8b8f71.png)
![image](https://user-images.githubusercontent.com/21196249/43226260-586481fa-9029-11e8-996a-e635079394a3.png)
![image](https://user-images.githubusercontent.com/21196249/43226321-8d05e0ac-9029-11e8-96d4-4832fe2ac5e0.png)
![image](https://user-images.githubusercontent.com/21196249/43226345-9d6342be-9029-11e8-9cf0-a9b03a6c7ffe.png)
![image](https://user-images.githubusercontent.com/21196249/43226497-0cd28cfe-902a-11e8-83e5-3e6b98108449.png)
### Evaluar Proyecto Ingresado
![image](https://user-images.githubusercontent.com/21196249/43226901-2233a92e-902b-11e8-8131-2f5f40ac7833.png)
@felipedonoso @pabloespinoza 
Revisando Proyecto "Usted Sabe"

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
Se continua con Proyecto "Usted Sabe"
### Evaluar Proyecto Ingresado
![image](https://user-images.githubusercontent.com/21196249/43267426-ecacb228-90bb-11e8-8ea5-9622dd3e8664.png)
### Postular
![image](https://user-images.githubusercontent.com/21196249/43285965-9ddfd200-90ee-11e8-8fd9-554be7647567.png)
![image](https://user-images.githubusercontent.com/21196249/43286063-e22091ac-90ee-11e8-9575-db7b90f88d78.png)
### Proyecto 1800042036 Postulado
![image](https://user-images.githubusercontent.com/21196249/43286170-339393d6-90ef-11e8-8d29-2ef320572c70.png)
### Evaluar Pre Seleccionado
![image](https://user-images.githubusercontent.com/21196249/43287115-07de959e-90f2-11e8-8cfd-97f1c7a31cce.png)
![image](https://user-images.githubusercontent.com/21196249/43287244-7065586e-90f2-11e8-9eeb-01f40324a8e2.png)
![image](https://user-images.githubusercontent.com/21196249/43287276-9d7107ea-90f2-11e8-8dfb-698eaf1ab4ad.png)
### Evaluar Proyecto Seleccionado
![image](https://user-images.githubusercontent.com/21196249/43287390-edb03d20-90f2-11e8-9566-21441ebea2a6.png)
![image](https://user-images.githubusercontent.com/21196249/43287425-09dabd40-90f3-11e8-8150-28361d401979.png)
![image](https://user-images.githubusercontent.com/21196249/43287520-49632aa6-90f3-11e8-8026-42a2ed1b912c.png)
![image](https://user-images.githubusercontent.com/21196249/43287588-7bbe477e-90f3-11e8-90d3-170945142961.png)
### Evaluar Proyecto Aprobado
![image](https://user-images.githubusercontent.com/21196249/43287743-e5e38ace-90f3-11e8-959e-d8e008b41be4.png)
![image](https://user-images.githubusercontent.com/21196249/43287818-1fb615be-90f4-11e8-887b-95037ceb5b40.png)
### Reporte Antes SC
[Proyecto - 1800042036_AntesSC.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/2233561/Proyecto.-.1800042036_AntesSC.pdf)
Después se continuará con este Proyecto 1800042036
