### ISSUE TITLE
Estudio de las tablas principales para levantar concurso 2017

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017#9]
Esta tarea tiene como fin estudiar cuales son las tablas implicadas para levantar el concurso del año 2017

**Comment by felipedonoso** [comment]
Las primeras tablas a cargar son las siguientes:

![image](https://cloud.githubusercontent.com/assets/5757157/18141486/0acfc082-6f90-11e6-85fc-7fdf00aed75a.png)

Para la creación del concurso son las siguientes:

![image](https://cloud.githubusercontent.com/assets/5757157/18142863/c550f0fc-6f95-11e6-8fc2-746b0a693435.png)

@pabloespinoza hay que revisar estas tablas dame tú opinión y con este se empezará a levantar el concurso y tener una primera iteración del concurso Alto Rendimiento 2017.

**Comment by felipedonoso** [comment]
@pabloespinoza hay que revisar el código para saber que validaciones realiza al momento de "presionar Nuevo Proyecto", que validaciones realiza y a que tabla va, mientras tanto estoy revisando el flujo cómo debería ser para que después lo analicemos. Avísame cuando tengas novedades.

**Comment by felipedonoso** [comment]
@pabloespinoza Necesito saber que tablas influyen al crear un nuevo proyecto con financiamiento del año siguiente, debería ser de esta manera:


1. Hacer un registro en la tabla programa, replicar el registro pero con año 2017.
2. Crear las líneas para el programa, para este caso solamente una, la de Administración:  idLinea=7, tabla Linea.
3. En la tabla linea_cuenta, hay que realizar la misma tarea(REPLICAR) que en la tabla "Linea".
4. En la tabla Cuenta, dejar así tal cuál.
5. Crear nuevo concurso en la tabla Concurso, replicar  el año anterior.
6. Crear nuevo concurso_categoria con el nuevo idConcurso.
7. Mantener la tabla categoria
8. Crear un registro Organizacion_linea, con una federación de prueba y para la línea=7 mencionada anteriormente.

Con esto podremos determinar cuales son las tablas criticas,

Favor de comentarme las tablas que utilizaste al crear un **nuevo proyecto**.

Saludos,

**Comment by felipedonoso** [comment]
@pabloespinoza, puedes verificar este flujo al momento de crear un proyecto, si no es igual favor de indicarme las diferencias.

Este es el flujo que debería y no necesariamente sea igual:

![image](https://cloud.githubusercontent.com/assets/5757157/18385075/b37c02ba-7664-11e6-9a19-080afb93b9c5.png)

**Comment by felipedonoso** [comment]
@pabloespinoza Favor de revisar si corresponde con el diagrama, de no ser así conversamos las diferencias.

**Comment by pabloespinoza** [comment]
Felipe,
     El punto 8 se debe modificar:
Crear un registro en Organizacion_linea, con una federación de prueba con idConcursoCategoria e idLinea creado anteriormente.

**Comment by felipedonoso** [comment]
@pabloespinoza, muy bien Pablo ahora como lo conversamos hay que seguir con el Folio que se le asigna a un proyecto.

## Este Folio vendrá dado de la siguiente manera:

# Ej: 2016 00 042 429

En donde 2016, corresponde al campo **_conAno de la tabla concurso_**:

![image](https://cloud.githubusercontent.com/assets/5757157/18714700/08a1b190-7fed-11e6-8675-e469d5ec8dda.png)

Luego, el dato **_'00'_**, corresponde al nivel nacional, se necesitará crear una tabla llamada **_"categoria_region"_**, la cuál nos permitirá más adelante escalar a una categoría por ejemplo **_"Asignación Directa"_**  y con esto podrá financiarse en otras regiones y no en el nivel central.

Estás son las tablas que alimentarán a **_"categoria_region"_**;

![image](https://cloud.githubusercontent.com/assets/5757157/18715178/b779e34e-7fee-11e6-831f-32bc1df39061.png)

Ahora el dato **_"042"_**, este vendrá de la tabla  **_"categoria"_**. Hay que modificar el campo, **catCodigoCategoria**  de  **_"04" => "042"_**.

![image](https://cloud.githubusercontent.com/assets/5757157/18715294/27e07c9c-7fef-11e6-81b6-9a9d52462158.png)


## Con esto se podrá saber mediante el folio del proyecto, en que concurso se postulo, la categoría y en donde se financiara.

**Comment by pabloespinoza** [comment]
@felipedonoso, para los últimos tres dígitos del folio se utilizara un trigger para que cuando se inserte un registro en la tabla Concurso_Categoria, se cree automáticamente una sequence que sirva de correlativo para ese concurso y esa categoría.
El nombre de estas secuencias serán SecuenciaAltoRendimientoPostulacion + idConcursoCategoria.

Ademas se debe realizar un SP que arroje como resultado el correlativo del concurso y categoría correspondiente. Este SP ademas debe aumentar la secuencia en 1.

**Comment by felipedonoso** [comment]
@pabloespinoza, la duda que tengo ahora es saber cuando la Federación presiona crear nuevo proyecto y selecciona la línea, cómo el sabe que hay presupuesto?

1. ¿Lee de la tabla **CUENTA (_campo ctaPresupuestoVigente_)** y resta todo lo asignado en la tabla **montos_organizacion_linea**?
2. ¿Opción 2, lee desde la tabla **LINEA (_campo linPresupuesto_)** y de ahí le resta todo lo asignado en la tabla **montos_organizacion_linea**?

**Comment by pabloespinoza** [comment]
@felipedonoso no se contemplara la tabla "categoria_region" y se actualizaran todos los código de región a "00", con esto, el folio de proyecto queda completamente dinámico.

**Comment by pabloespinoza** [comment]
Esta actualización se encuentra en ambiente QA lista para realizar las pruebas.

**Comment by felipedonoso** [comment]
@pabloespinoza ingrese al sitio: http://10.15.1.51/AltoRendimientoQA

Usuario: 16645373

**Y al agregar un nuevo proyecto:**

![image](https://cloud.githubusercontent.com/assets/5757157/19361138/d25a3d06-9157-11e6-9d28-1a4d4d6f7aa4.png)

Y al seleccionar cualquiera de los dos concursos no fue posible crear un proyecto, la lista desplegable de línea tampoco se cargo.

No se pudo continuar con la prueba.

**Comment by pabloespinoza** [comment]
@felipedonoso , se encuentra corregido y listo para probar.

**Comment by felipedonoso** [comment]
Creando un proyecto año 2017 para Administración:

![image](https://cloud.githubusercontent.com/assets/5757157/19364264/d5b64c72-9163-11e6-94d6-9f5430f6af36.png)

![image](https://cloud.githubusercontent.com/assets/5757157/19364388/5ef4b064-9164-11e6-999f-dda74b45d6f9.png)


### Reporte del Proyecto antes de postular:
[Proyecto - 0 (1).pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/528072/Proyecto.-.0.1.pdf)

Quitale eso por fa:

![image](https://cloud.githubusercontent.com/assets/5757157/19364794/003bc6fa-9166-11e6-8fe4-7af9d27a2d05.png)

### No aparece la opción de agregar todos:

![image](https://cloud.githubusercontent.com/assets/5757157/19364834/3cfbc5ae-9166-11e6-93ae-64642d6474cc.png)


No se refresca el mensaje ya que se han asignado a todos los beneficiarios la geolocalización:

![image](https://cloud.githubusercontent.com/assets/5757157/19364945/c393eb6e-9166-11e6-91e4-2ea62dbb530f.png)

Listo para ### postular:

![image](https://cloud.githubusercontent.com/assets/5757157/19364964/d98a26d6-9166-11e6-86a6-8e63179dca60.png)

Resultado al ### postular:

![image](https://cloud.githubusercontent.com/assets/5757157/19364987/f85261c8-9166-11e6-972b-8834d2c6b8f9.png)

Reporte una vez postulado:

[Proyecto - 1700042010.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/528103/Proyecto.-.1700042010.pdf)


@pabloespinoza la prueba fue satisfactoria, adjunto mejoras que hacer que las colocare en otras tareas.

mañana @danteghirardelli nos ayudará con otra prueba

**Comment by felipedonoso** [comment]
@danteghirardelli favor de crear al menos 02 proyectos para la **_línea: Art. 1º ley 19135 Fed. Dep. Nacional_**:

Favor de tener los siguientes gastos:

**En personal:**
Honorarios
Remuneración

**Bienes y Servicios**
Asignaciones especiales
Viáticos
Alojamientos
combustibles...

Luego cargare otras líneas para realizar las mismas pruebas:

**Comment by felipedonoso** [comment]
# Revisando los 08 pasos:

## 1. Hacer un registro en la tabla programa, replicar el registro pero con año 2017.

En la tabla programa se observa lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/19391828/9a55de76-9204-11e6-87fe-8cf7ba0c508a.png)

### El paso 1 esta OK

## 2. Crear las líneas para el programa, para este caso solamente una, la de Administración:

En la tabla programa se observa lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/19392007/511c951e-9205-11e6-90b7-cdb5237823be.png)

### El paso 2 esta OK

## 3. En la tabla linea_cuenta, hay que realizar la misma tarea(REPLICAR) que en la tabla "Linea".

En la tabla programa se observa lo siguiente:

![image](https://cloud.githubusercontent.com/assets/5757157/19392116/c9dc8356-9205-11e6-83da-4888bfac8dbf.png)

### El paso 3 esta OK

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

![image](https://cloud.githubusercontent.com/assets/21196249/19389957/67e7fb34-91fc-11e6-96f0-5b1a7550b05c.png)

## Proyecto Racing 2016
![image](https://cloud.githubusercontent.com/assets/21196249/19390166/47ff3eb2-91fd-11e6-84e5-9b94b5002db8.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19390231/9217818a-91fd-11e6-8df2-76bb0e8ded5f.png)

Producto
![image](https://cloud.githubusercontent.com/assets/21196249/19390336/111ca7bc-91fe-11e6-8dfa-c4923a7d3a7d.png)


![image](https://cloud.githubusercontent.com/assets/21196249/19390528/daef5a62-91fe-11e6-87a1-1a7c5dd6046e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19390583/1275465e-91ff-11e6-9f1e-3180ed8690ac.png)


Asignar Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/19390638/522f2d3c-91ff-11e6-89a3-abe53c783e29.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19390688/8b42fa86-91ff-11e6-983a-c647f7d96a28.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19390723/b6fdf1ee-91ff-11e6-8671-105302fa0713.png)

Gastos Personales
![image](https://cloud.githubusercontent.com/assets/21196249/19390791/022c1c7c-9200-11e6-83af-c24a24a4f979.png)

Nuevo Registro
![image](https://cloud.githubusercontent.com/assets/21196249/19390994/ee4a694c-9200-11e6-8bbf-e081f655e4ec.png)

Remuneración
![image](https://cloud.githubusercontent.com/assets/21196249/19391631/e1f0f41a-9203-11e6-8c66-30e1f7c56e0f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19391713/26496b9c-9204-11e6-8321-d369d50da9d0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19391816/876f8f64-9204-11e6-8ce2-8e52990acc09.png)

## Gastos en Bienes y Servicios

![image](https://cloud.githubusercontent.com/assets/21196249/19392214/34b3f218-9206-11e6-8e81-d40af771c319.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19392260/676aecca-9206-11e6-8a34-0d782f36c1ba.png)


Asignaciones Especiales
![image](https://cloud.githubusercontent.com/assets/21196249/19392407/097c83e8-9207-11e6-810d-9256ce5d0078.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19392484/4c907cac-9207-11e6-92ef-a7eec01d5ec6.png)

Nuevo Gasto

![image](https://cloud.githubusercontent.com/assets/21196249/19392569/ab3736ce-9207-11e6-88e6-f64f109f985c.png)

Viáticos
![image](https://cloud.githubusercontent.com/assets/21196249/19392666/209fa50e-9208-11e6-855e-fad9ee18c5df.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19392829/c3c18978-9208-11e6-8232-44f7e3eea64f.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19393120/c998bd7a-9209-11e6-9100-0adcecf45326.png)

“No se puede ingresar Alimentación y Hospedaje por que tiene ingresado el ítem Viático”

### Arreglar mensaje"por que" por "porque".


## Combustibles, Lubricantes,Peajes y Pasajes. 
![image](https://cloud.githubusercontent.com/assets/21196249/19393432/16b83d78-920b-11e6-80b2-94c63060f423.png)


![image](https://cloud.githubusercontent.com/assets/21196249/19393645/fd70b93e-920b-11e6-88e1-4c970732fced.png)

Verificar y Postular
![image](https://cloud.githubusercontent.com/assets/21196249/19393792/9fd70732-920c-11e6-8842-a80670c8215b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19393865/fc694a46-920c-11e6-8626-d686b23519de.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19393897/20ef63d2-920d-11e6-87c3-c729e2eac040.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19393923/40e8ec30-920d-11e6-9382-8720f1aaa547.png)

Proyecto "Racing 2016" Código 1700042011 en estado "Postulado" listo.

Adjunto reporte:

[Proyecto - 1700042011.pdf](https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/files/529920/Proyecto.-.1700042011.pdf)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

##  Crear Nuevo Proyecto Sao Paulo
 
![image](https://cloud.githubusercontent.com/assets/21196249/19399606/bfe7e660-9228-11e6-8d23-48eb3aa67887.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19399617/cb01546e-9228-11e6-94d9-c58be90168ca.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19399786/916d7100-9229-11e6-8e4f-f27229cabbea.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19399820/b8366382-9229-11e6-8c22-db2a9e3626cf.png)

## Producto
![image](https://cloud.githubusercontent.com/assets/21196249/19400044/b543099a-922a-11e6-8e35-ceaa3d8dfa5e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19400233/a7ca5290-922b-11e6-9c76-f5a5783e74c7.png)

 
![image](https://cloud.githubusercontent.com/assets/21196249/19400327/0dc778ca-922c-11e6-8081-00b73135f603.png)

Asignación ### Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/19400379/5515b6f6-922c-11e6-8cd3-bb2861440552.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19400416/86067e9e-922c-11e6-95da-5bc37ad086a5.png)

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 
## Continuación de Proyecto "Sao Paulo" 

![image](https://cloud.githubusercontent.com/assets/21196249/19437533/2535f8c0-944c-11e6-9f1c-62a87e3114d6.png)

## Gastos Personal
![image](https://cloud.githubusercontent.com/assets/21196249/19437607/7dd3199a-944c-11e6-97d4-e09d118c5e67.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19437645/b2142564-944c-11e6-9758-03d4711067c2.png)

## Honorarios

![image](https://cloud.githubusercontent.com/assets/21196249/19437887/b05565de-944d-11e6-92e6-fe74b1168aa7.png)

Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/19438078/838ed57a-944e-11e6-8996-1f70d839af7c.png)

## Remuneración
![image](https://cloud.githubusercontent.com/assets/21196249/19438229/330992ba-944f-11e6-870e-ec58dace2cef.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19438276/7109ec9a-944f-11e6-80cc-584cc0224e00.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19438317/a8cfe4b8-944f-11e6-877b-fac3d84085ae.png)

## Gastos en Bienes y Servicios
![image](https://cloud.githubusercontent.com/assets/21196249/19438750/cbe30ce4-9451-11e6-8196-556054185f3f.png)

Listado de Gasto de Administración
![image](https://cloud.githubusercontent.com/assets/21196249/19438872/41a14cca-9452-11e6-8d41-1871cf345915.png)

## Alimentación y Alojamiento
![image](https://cloud.githubusercontent.com/assets/21196249/19439237/c668d404-9453-11e6-81ce-0dc3d6df9076.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19439286/f7c282f2-9453-11e6-9783-9a3149577f68.png)

**## Verificar y Postular**
![image](https://cloud.githubusercontent.com/assets/21196249/19439771/c701674e-9455-11e6-9d05-7327814d5dc5.png)

## Resumen General
![image](https://cloud.githubusercontent.com/assets/21196249/19439883/28b8c5c2-9456-11e6-854f-1cb810f5124b.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19439965/784a5f60-9456-11e6-9a8d-759a5982a8aa.png)

Proyecto Sao Paulo  Código 1700042012 Estado “Postulado”.

![image](https://cloud.githubusercontent.com/assets/21196249/19440396/22335724-9458-11e6-9104-f5d97d22b27e.png)

**Comment by felipedonoso** [comment]
@pabloespinoza, 

Modificar el mensaje "Arreglar mensaje"por que" por "porque"." esto ocurre al crear un gasto en Bienes y Servicios.

@danteghirardelli ahora favor de crear un proyecto pero con la línea de plan de desarrollo estratégico:

**Comment by danteghirardelli** [comment]
@felipedonoso @pabloespinoza 

OK Felipe cuando lo tengas cargado me avisas.
Saludos.

**Comment by danteghirardelli** [comment]
## Proyecto PDE

![image](https://cloud.githubusercontent.com/assets/21196249/19444762/303d1ec6-9468-11e6-8033-982dd1100fc8.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19444929/ce2c7910-9468-11e6-8bd7-29ee567edbf1.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19445021/2385ed92-9469-11e6-8447-128b63129171.png)
## Producto

![image](https://cloud.githubusercontent.com/assets/21196249/19445040/3481ef9c-9469-11e6-8f99-f339059b1931.png)

![image](https://cloud.githubusercontent.com/assets/21196249/19445306/1c663462-946a-11e6-8c01-4532250c54cf.png)

@felipedonoso @pabloespinoza 

## No aparecen Los Productos
![image](https://cloud.githubusercontent.com/assets/21196249/19446399/e7858e1e-946e-11e6-97f2-c10aa220c8c5.png)

**Comment by felipedonoso** [comment]
# Hay que revisar si se cumple con esta tarea:

https://github.com/InstitutoNacionalDeDeportes/PostulacionAltoRendimiento2017/issues/9

# Se cierra esta tarea solamente queda pendiente: 

haber hecho una prueba con los productos cargados a una línea nueva:
